/*
 * SDialogDiotLayout.java
 *
 * Created on 29/06/2010, 05:02:26 PM
 */

package erp.mfin.data.diot;

import erp.data.SDataConstants;
import erp.data.SDataReadDescriptions;
import erp.gui.SGuiUtilities;
import erp.lib.SLibConstants;
import erp.lib.SLibTimeUtilities;
import erp.lib.SLibUtilities;
import erp.lib.form.SFormField;
import erp.lib.form.SFormUtilities;
import erp.lib.form.SFormValidation;
import erp.mfin.data.SDataTax;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sa.lib.SLibUtils;

/**
 * For DIOT layout valid until 2024-12-31.
 * @author Sergio Flores, Isabel Servín, Sergio Flores
 */
public class SDialogDiotLayout extends javax.swing.JDialog implements java.awt.event.ActionListener {

    private final erp.client.SClientInterface miClient;
    private final int mnDiotVersion;
    private erp.lib.form.SFormField moFieldDateStart;
    private erp.lib.form.SFormField moFieldDateEnd;
    private java.util.Vector<erp.lib.form.SFormField> mvFields;
    private SDataTax moConfigDiotTax;
    private String[] msConfigDiotAccounts;
    private int[] manConfigDiotTaxRegionsIgnored;

    /** Creates new form SDialogDiotLayout
     * @param client GUI client.
     * @param diotVersion Supported options: constants SDiotConsts.VER_1 & SDiotConsts.VER_2.
     */
    public SDialogDiotLayout(erp.client.SClientInterface client, int diotVersion) {
        super(client.getFrame(), false);
        miClient = client;
        mnDiotVersion = diotVersion;
        initComponents();
        initComponentsExtra();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFormat = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlDateStart = new javax.swing.JLabel();
        jftDateStart = new javax.swing.JFormattedTextField();
        jbPickDateStart = new javax.swing.JButton();
        jlDummy = new javax.swing.JLabel();
        jckExcludeTotallyZero = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jlDateEnd = new javax.swing.JLabel();
        jftDateEnd = new javax.swing.JFormattedTextField();
        jbPickDateEnd = new javax.swing.JButton();
        jlFormat = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jrbFormatCsv = new javax.swing.JRadioButton();
        jPanel13 = new javax.swing.JPanel();
        jrbFormatPipe = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jspDiotConfig = new javax.swing.JScrollPane();
        jtaDiotConfig = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jspWarnings = new javax.swing.JScrollPane();
        jtaWarnings = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jbSave = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Layout de la DIOT");
        setResizable(false);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros para generar el layout de la DIOT:"));
        jPanel6.setLayout(new java.awt.GridLayout(5, 1, 0, 5));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDateStart.setText("Fecha inicial: *");
        jlDateStart.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel3.add(jlDateStart);

        jftDateStart.setText("dd/mm/yyyy");
        jftDateStart.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel3.add(jftDateStart);

        jbPickDateStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erp/img/cal_cal.gif"))); // NOI18N
        jbPickDateStart.setToolTipText("Seleccionar fecha");
        jbPickDateStart.setFocusable(false);
        jbPickDateStart.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel3.add(jbPickDateStart);

        jlDummy.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel3.add(jlDummy);

        jckExcludeTotallyZero.setText("Excluir del layout a terceros totalmente en cero");
        jckExcludeTotallyZero.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel3.add(jckExcludeTotallyZero);

        jPanel6.add(jPanel3);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDateEnd.setText("Fecha final: *");
        jlDateEnd.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel8.add(jlDateEnd);

        jftDateEnd.setText("dd/mm/yyyy");
        jftDateEnd.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel8.add(jftDateEnd);

        jbPickDateEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erp/img/cal_cal.gif"))); // NOI18N
        jbPickDateEnd.setToolTipText("Seleccionar fecha");
        jbPickDateEnd.setFocusable(false);
        jbPickDateEnd.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel8.add(jbPickDateEnd);

        jPanel6.add(jPanel8);

        jlFormat.setText("Formato del archivo:");
        jPanel6.add(jlFormat);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        bgFormat.add(jrbFormatCsv);
        jrbFormatCsv.setText("Valores sin redondear, separados por coma (CSV) + resumen informativo y lista de excepciones");
        jrbFormatCsv.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel14.add(jrbFormatCsv);

        jPanel6.add(jPanel14);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        bgFormat.add(jrbFormatPipe);
        jrbFormatPipe.setText("Valores redondeados, separados por el carácter | (\"pipe\" o \"barra vertical\")");
        jrbFormatPipe.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel13.add(jrbFormatPipe);

        jPanel6.add(jPanel13);

        jPanel2.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración actual para la DIOT:"));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jspDiotConfig.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspDiotConfig.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jspDiotConfig.setPreferredSize(new java.awt.Dimension(100, 100));

        jtaDiotConfig.setEditable(false);
        jtaDiotConfig.setBackground(java.awt.SystemColor.control);
        jtaDiotConfig.setColumns(20);
        jtaDiotConfig.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jtaDiotConfig.setLineWrap(true);
        jtaDiotConfig.setRows(5);
        jtaDiotConfig.setText("1) IVA predeterminado para la DIOT: ...\n\n2) Cuentas contables para la DIOT: ...\n\n3) Regiones de impuestos ignoradas para la DIOT:...");
        jtaDiotConfig.setWrapStyleWord(true);
        jspDiotConfig.setViewportView(jtaDiotConfig);

        jPanel7.add(jspDiotConfig, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7, java.awt.BorderLayout.NORTH);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Advertencias en la generación del layout de la DIOT:"));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jspWarnings.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspWarnings.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jtaWarnings.setEditable(false);
        jtaWarnings.setBackground(java.awt.SystemColor.control);
        jtaWarnings.setColumns(20);
        jtaWarnings.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jtaWarnings.setLineWrap(true);
        jtaWarnings.setRows(5);
        jtaWarnings.setText("1) Los importes de pagos realizados a operaciones de IVA tasa 0 o exento que en su momento fueron provisionadas equivocadamente a otras tasas de IVA, p. ej., a tasa general, pero intencionalmente manipuladas para que el monto del IVA fuera igual a cero, serán por defecto clasificados como operaciones de IVA tasa 0 en el archivo del layout de la DIOT.\n\n2) Los importes de pagos realizados a operaciones de IVA tasa 0 o exento que en su momento fueron provisionadas simultáneamente en el mismo asiento contable con operaciones a otras tasas de IVA, p. ej., a tasa general, serán por defecto clasificados como operaciones de IVA exento en el archivo del layout de la DIOT.");
        jtaWarnings.setWrapStyleWord(true);
        jspWarnings.setViewportView(jtaWarnings);

        jPanel5.add(jspWarnings, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jbSave.setText("Generar");
        jbSave.setToolTipText("[Ctrl + Enter]");
        jbSave.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel1.add(jbSave);

        jbCancel.setText("Cancelar");
        jbCancel.setToolTipText("[Escape]");
        jPanel1.add(jbCancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(736, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsExtra() {
        moFieldDateStart = new SFormField(miClient, SLibConstants.DATA_TYPE_DATE, true, jftDateStart, jlDateStart);
        moFieldDateStart.setPickerButton(jbPickDateStart);
        moFieldDateEnd = new SFormField(miClient, SLibConstants.DATA_TYPE_DATE, true, jftDateEnd, jlDateEnd);
        moFieldDateEnd.setPickerButton(jbPickDateEnd);

        mvFields = new Vector<>();
        mvFields.add(moFieldDateStart);
        mvFields.add(moFieldDateEnd);

        jbPickDateStart.addActionListener(this);
        jbPickDateEnd.addActionListener(this);
        jbSave.addActionListener(this);
        jbCancel.addActionListener(this);

        moFieldDateStart.setFieldValue(SLibTimeUtilities.getBeginOfMonth(miClient.getSessionXXX().getWorkingDate()));
        moFieldDateEnd.setFieldValue(SLibTimeUtilities.getEndOfMonth(miClient.getSessionXXX().getWorkingDate()));
        jckExcludeTotallyZero.setSelected(true);
        jrbFormatCsv.setSelected(true);
        
        if (mnDiotVersion == SDiotConsts.VER_2) {
            setTitle("Layout de la DIOT 2025");
        }
        
        processConfig();
                
        SFormUtilities.createActionMap(rootPane, this, "actionPerformedPrint", "print", KeyEvent.VK_ENTER, KeyEvent.CTRL_DOWN_MASK);
        SFormUtilities.createActionMap(rootPane, this, "actionPerformedCancel", "cancel", KeyEvent.VK_ESCAPE, 0);
    }
    
    private void processConfig() {
        moConfigDiotTax = null;
        msConfigDiotAccounts = null;
        manConfigDiotTaxRegionsIgnored = null;

        String diotConfig = "";
        
        try {
            // process DIOT tax:
            
            moConfigDiotTax = SDiotUtils.getDiotVatDefault(miClient);
            
            diotConfig = "1) IVA predeterminado para la DIOT: " + (moConfigDiotTax != null ? moConfigDiotTax.getTax() + " "
                    + "(PK: " + SLibUtils.textKey((int[]) moConfigDiotTax.getPrimaryKey()) + ")" : "ND");
            
            // process DIOT accounts:
            
            String accounts = "";
            
            msConfigDiotAccounts = SDiotUtils.getDiotAccounts(miClient.getSession().getStatement());
            
            if (msConfigDiotAccounts.length == 1 && msConfigDiotAccounts[0].isEmpty()) {
                msConfigDiotAccounts = null;
            }
            else {
                for (int i = 0; i < msConfigDiotAccounts.length; i++) {
                    if (!msConfigDiotAccounts[i].isEmpty()) {
                        accounts += (accounts.isEmpty() ? "" : (i + 1 < msConfigDiotAccounts.length ? ", " : " y ")) + msConfigDiotAccounts[i];
                    }
                }
            }
            
            diotConfig += "\n\n2) Cuentas contables para la DIOT: " + (!accounts.isEmpty() ? accounts : "ND");
            
            // process DIOT tax regions ignored:
            
            String taxRegionsIgnored = "";
            
            manConfigDiotTaxRegionsIgnored = SDiotUtils.getDiotTaxRegionsIgnored(miClient.getSession().getStatement());
            
            if (manConfigDiotTaxRegionsIgnored != null) {
                for (int i = 0; i < manConfigDiotTaxRegionsIgnored.length; i++) {
                    taxRegionsIgnored += (taxRegionsIgnored.isEmpty() ? "" : (i + 1 < manConfigDiotTaxRegionsIgnored.length ? ", " : " y ")) + SDataReadDescriptions.getCatalogueDescription(miClient, SDataConstants.FINU_TAX_REG, new int[] { manConfigDiotTaxRegionsIgnored[i] }) + " "
                            + "(PK: " + manConfigDiotTaxRegionsIgnored[i] + ")";
                }
            }
            
            diotConfig += "\n\n3) Regiones de impuestos ignoradas para la DIOT: " + (!taxRegionsIgnored.isEmpty() ? taxRegionsIgnored : "ND");
        }
        catch (Exception e) {
            SLibUtilities.renderException(this, e);
        }
        
        jtaDiotConfig.setText(!diotConfig.isEmpty() ? diotConfig : "ND");
        jtaDiotConfig.setCaretPosition(0);
    }
    
    @SuppressWarnings("deprecation")
    private void computeLayout() {
        try {
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            
            String layout;
            String charset;
            
            switch (mnDiotVersion) {
                case SDiotConsts.VER_1:
                    layout = new erp.mfin.data.diot.ver1.SDiotLayout(miClient, 
                            moFieldDateStart.getDate(), 
                            moFieldDateEnd.getDate()).getLayout(jrbFormatPipe.isSelected() ? SDiotConsts.FORMAT_PIPE : SDiotConsts.FORMAT_CSV,
                            jckExcludeTotallyZero.isSelected());
                    charset = "ASCII";
                    break;
                    
                case SDiotConsts.VER_2:
                    layout = new erp.mfin.data.diot.ver2.SDiotLayout(miClient, 
                            moFieldDateStart.getDate(), 
                            moFieldDateEnd.getDate()).getLayout(jrbFormatPipe.isSelected() ? SDiotConsts.FORMAT_PIPE : SDiotConsts.FORMAT_CSV,
                            jckExcludeTotallyZero.isSelected());
                    charset = "UTF-8";
                    break;
                    
                default:
                    throw new Exception(SLibConstants.MSG_ERR_UTIL_UNKNOWN_OPTION);
            }
            
            String fileExt = jrbFormatPipe.isSelected() ? ".txt" : ".csv";
            SimpleDateFormat periodFormat = new SimpleDateFormat("yyyy-MM");

            miClient.getFileChooser().setSelectedFile(
                    new File("DIOT " +
                            miClient.getSessionXXX().getCompany().getDbmsDataCompany().getFiscalId() + " " +
                            periodFormat.format(moFieldDateEnd.getDate()) + " " +
                            SLibUtils.FileDateFormatDatetime.format(new Date()) +
                            fileExt));

            if (miClient.getFileChooser().showSaveDialog(miClient.getFrame()) == JFileChooser.APPROVE_OPTION) {
                String fileName = miClient.getFileChooser().getSelectedFile().getAbsolutePath();

                File file = new File(fileName.endsWith(fileExt) ? fileName : fileName + fileExt);

                try (BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file), charset))) {
                    bw.write(layout);
                }
                
                if (miClient.showMsgBoxConfirm(SLibConstants.MSG_INF_FILE_CREATE + file.getPath() + "\n" + SLibConstants.MSG_CNF_FILE_OPEN) == JOptionPane.YES_OPTION) {
                    SLibUtilities.launchFile(file.getPath());
                }
            }
        }
        catch (Exception e) {
            SLibUtils.showException(this, e);
        }
        finally {
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }

    private void actionPerformedDateBegin() {
        miClient.getGuiDatePickerXXX().pickDate(moFieldDateStart.getDate(), moFieldDateStart);
    }

    private void actionPerformedDateEnd() {
        miClient.getGuiDatePickerXXX().pickDate(moFieldDateEnd.getDate(), moFieldDateEnd);
    }

    public void actionPerformedSave() {
        SFormValidation validation = validateDialog();

        if (validation.getIsError()) {
            if (validation.getComponent() != null) {
                validation.getComponent().requestFocus();
            }
            if (!validation.getMessage().isEmpty()) {
                miClient.showMsgBoxWarning(validation.getMessage());
            }
        }
        else {
            computeLayout();
            setVisible(false);
        }
    }

    public void actionPerformedCancel() {
        setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFormat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbPickDateEnd;
    private javax.swing.JButton jbPickDateStart;
    private javax.swing.JButton jbSave;
    private javax.swing.JCheckBox jckExcludeTotallyZero;
    private javax.swing.JFormattedTextField jftDateEnd;
    private javax.swing.JFormattedTextField jftDateStart;
    private javax.swing.JLabel jlDateEnd;
    private javax.swing.JLabel jlDateStart;
    private javax.swing.JLabel jlDummy;
    private javax.swing.JLabel jlFormat;
    private javax.swing.JRadioButton jrbFormatCsv;
    private javax.swing.JRadioButton jrbFormatPipe;
    private javax.swing.JScrollPane jspDiotConfig;
    private javax.swing.JScrollPane jspWarnings;
    private javax.swing.JTextArea jtaDiotConfig;
    private javax.swing.JTextArea jtaWarnings;
    // End of variables declaration//GEN-END:variables


    public SFormValidation validateDialog() {
        SFormValidation validation = new SFormValidation();
        
        if (moConfigDiotTax == null) {
            validation.setMessage("¡No se puede generar la DIOT!:\n"
                    + "No se ha definido en la configuración de la empresa el IVA predeterminado para la DIOT.");
        }
        else if (msConfigDiotAccounts == null) {
            validation.setMessage("¡No se puede generar la DIOT!:\n"
                    + "No se han definido en la configuración de la empresa las cuentas contables para la DIOT.");
        }
        else {
            for (SFormField field : mvFields) {
                if (!field.validateField()) {
                    validation.setIsError(true);
                    validation.setComponent(field.getComponent());
                    break;
                }
            }

            if (!validation.getIsError()) {
                String message = SGuiUtilities.validateDateRange(moFieldDateStart.getDate(), moFieldDateEnd.getDate());

                if (!message.isEmpty()) {
                    validation.setMessage(message);
                    validation.setComponent(jftDateEnd);
                }
            }
        }
        
        return validation;
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            JButton button = (JButton) e.getSource();

            if (button == jbPickDateStart) {
                actionPerformedDateBegin();
            }
            else if (button == jbPickDateEnd) {
                actionPerformedDateEnd();
            }
            else if (button == jbSave) {
                actionPerformedSave();
            }
            else if (button == jbCancel) {
                actionPerformedCancel();
            }
        }
    }
}
