/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.mod.log.form;

import erp.lib.SLibConstants;
import erp.mod.SModConsts;
import erp.mod.log.db.SDbSpot;
import sa.lib.SLibConsts;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;

/**
 *
 * @author Néstor Ávalos
 */
public class SFormSpot extends sa.lib.gui.bean.SBeanForm {

    private SDbSpot moRegistry;

    /**
     * Creates new form SFormSpot
     */
    public SFormSpot(SGuiClient client, String title) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.LOGU_SPOT, SLibConstants.UNDEFINED, title);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jlDeliveryType = new javax.swing.JLabel();
        moKeyDeliveryType = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel21 = new javax.swing.JPanel();
        jlSpotType = new javax.swing.JLabel();
        moKeySpotType = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel22 = new javax.swing.JPanel();
        jlCode = new javax.swing.JLabel();
        moTextCode = new sa.lib.gui.bean.SBeanFieldText();
        jPanel24 = new javax.swing.JPanel();
        jlName = new javax.swing.JLabel();
        moTextName = new sa.lib.gui.bean.SBeanFieldText();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel23.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDeliveryType.setText("Tipo entrega:*");
        jlDeliveryType.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel25.add(jlDeliveryType);

        moKeyDeliveryType.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel25.add(moKeyDeliveryType);

        jPanel23.add(jPanel25);

        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlSpotType.setText("Tipo lugar:*");
        jlSpotType.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel21.add(jlSpotType);

        moKeySpotType.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel21.add(moKeySpotType);

        jPanel23.add(jPanel21);

        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCode.setText("Código:*");
        jlCode.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel22.add(jlCode);
        jPanel22.add(moTextCode);

        jPanel23.add(jPanel22);

        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlName.setText("Nombre:*");
        jlName.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel24.add(jlName);

        moTextName.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel24.add(moTextName);

        jPanel23.add(jPanel24);

        jPanel1.add(jPanel23, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlCode;
    private javax.swing.JLabel jlDeliveryType;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlSpotType;
    private sa.lib.gui.bean.SBeanFieldKey moKeyDeliveryType;
    private sa.lib.gui.bean.SBeanFieldKey moKeySpotType;
    private sa.lib.gui.bean.SBeanFieldText moTextCode;
    private sa.lib.gui.bean.SBeanFieldText moTextName;
    // End of variables declaration//GEN-END:variables

    private void initComponentsCustom() {
        SGuiUtils.setWindowBounds(this, 480, 300);

        moKeyDeliveryType.setKeySettings(miClient, SGuiUtils.getLabelName(jlDeliveryType.getText()), true);
        moKeySpotType.setKeySettings(miClient, SGuiUtils.getLabelName(jlSpotType.getText()), true);
        moTextCode.setTextSettings(SGuiUtils.getLabelName(jlCode.getText()), 10);
        moTextName.setTextSettings(SGuiUtils.getLabelName(jlName.getText()), 50);

        moFields.addField(moKeyDeliveryType);
        moFields.addField(moKeySpotType);
        moFields.addField(moTextCode);
        moFields.addField(moTextName);

        moFields.setFormButton(jbSave);
    }

    @Override
    public void addAllListeners() {

    }

    @Override
    public void removeAllListeners() {

    }

    @Override
    public void reloadCatalogues() {
        miClient.getSession().populateCatalogue(moKeyDeliveryType, SModConsts.LOGS_TP_DLY, SLibConsts.UNDEFINED, null);
        miClient.getSession().populateCatalogue(moKeySpotType, SModConsts.LOGS_TP_SPOT, SLibConsts.UNDEFINED, null);
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        moRegistry = (SDbSpot) registry;

        mnFormResult = SLibConsts.UNDEFINED;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();

        if (moRegistry.isRegistryNew()) {
            moRegistry.initPrimaryKey();
            jtfRegistryKey.setText("");
        }
        else {
            jtfRegistryKey.setText(SLibUtils.textKey(moRegistry.getPrimaryKey()));
        }

        moKeyDeliveryType.setValue(new int[] { moRegistry.getFkDeliveryTypeId() });
        moKeySpotType.setValue(new int[] { moRegistry.getFkSpotTypeId() });
        moTextCode.setValue(moRegistry.getCode());
        moTextName.setValue(moRegistry.getName());

        setFormEditable(true);

        if (moRegistry.isRegistryNew()) { }

        addAllListeners();
    }

    @Override
    public SDbRegistry getRegistry() throws Exception {
        SDbSpot registry = moRegistry.clone();

        if (registry.isRegistryNew()) {}

        moRegistry.setFkDeliveryTypeId(moKeyDeliveryType.getValue()[0]);
        moRegistry.setFkSpotTypeId(moKeySpotType.getValue()[0]);
        moRegistry.setCode(moTextCode.getValue());
        moRegistry.setName(moTextName.getValue());

        return registry;
    }

    @Override
    public SGuiValidation validateForm() {
        SGuiValidation validation = moFields.validateFields();

        return validation;
    }
}
