/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.mod.cfg.swap.form;

import erp.SFileUtilities;
import erp.mod.cfg.swap.SSwapConsts;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.Date;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import sa.lib.gui.bean.SBeanFormDialog;

/**
 *
 * @author Sergio Flores
 */
public class SDialogPdfViewer extends SBeanFormDialog implements ActionListener {
    
    protected static final float[] ZOOMS = new float[] { 2.5f, 2.0f, 1.5f, 1.0f, 0.75f }; // ≈ 200%, 150%, 100%, 75%, 50%
    protected static final int[] ZOOM_OPTIONS = new int[] { 150, 125, 100, 75, 50 }; // i.e., %
    protected static final int ZOOM_INDEX_100 = 2; // index in static member ZOOMS
    protected static final String TOOL_TIP_DOCUMENT = "Folio del documento";
    protected static final String TOOL_TIP_FILE = "Archivo PDF";
    
    protected boolean mbAllowDelettion;
    protected SDocument moDocument;
    protected File moPdf;
    protected PDDocument moPDDocument;
    protected PDFRenderer moPDFRenderer;
    protected JLabel moLabel;
    protected HashMap<String, BufferedImage> moPageImages;
    protected int mnPages;
    protected int mnCurrentPageIndex;
    protected int mnCurrentZoomIndex;

    /**
     * Creates new form SDialogPdfViewer
     * @param client
     * @param allowDeletion
     */
    public SDialogPdfViewer(final SGuiClient client, final boolean allowDeletion) {
        mbAllowDelettion = allowDeletion;
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, 0, 0, "Visor de PDF");
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfCurrentPage = new javax.swing.JTextField();
        jbGoFirstPage = new javax.swing.JButton();
        jbGoPrevPage = new javax.swing.JButton();
        jbGoNextPage = new javax.swing.JButton();
        jbGoLastPage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfCurrentZoom = new javax.swing.JTextField();
        jbZoomIn = new javax.swing.JButton();
        jbZoomReset = new javax.swing.JButton();
        jbZoomOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfDocument = new javax.swing.JTextField();
        jtfFile = new javax.swing.JTextField();
        jbFileSave = new javax.swing.JButton();
        jbFileInfo = new javax.swing.JButton();
        jbFileDeleteToUpdate = new javax.swing.JButton();
        jchkDeleteOnClose = new javax.swing.JCheckBox();
        jScrollPane = new javax.swing.JScrollPane();

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jtfCurrentPage.setEditable(false);
        jtfCurrentPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCurrentPage.setText("1/1");
        jtfCurrentPage.setToolTipText("Página actual");
        jtfCurrentPage.setFocusable(false);
        jtfCurrentPage.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel1.add(jtfCurrentPage);

        jbGoFirstPage.setText("|<");
        jbGoFirstPage.setToolTipText("Primera página");
        jbGoFirstPage.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbGoFirstPage.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel1.add(jbGoFirstPage);

        jbGoPrevPage.setText("<");
        jbGoPrevPage.setToolTipText("Página anterior");
        jbGoPrevPage.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbGoPrevPage.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel1.add(jbGoPrevPage);

        jbGoNextPage.setText(">");
        jbGoNextPage.setToolTipText("Página siguiente");
        jbGoNextPage.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbGoNextPage.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel1.add(jbGoNextPage);

        jbGoLastPage.setText(">|");
        jbGoLastPage.setToolTipText("Última página");
        jbGoLastPage.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbGoLastPage.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel1.add(jbGoLastPage);

        jLabel1.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel1.add(jLabel1);

        jtfCurrentZoom.setEditable(false);
        jtfCurrentZoom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCurrentZoom.setText("100%");
        jtfCurrentZoom.setToolTipText("Zoom actual");
        jtfCurrentZoom.setFocusable(false);
        jtfCurrentZoom.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel1.add(jtfCurrentZoom);

        jbZoomIn.setText("+");
        jbZoomIn.setToolTipText("Acercar");
        jbZoomIn.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbZoomIn.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel1.add(jbZoomIn);

        jbZoomReset.setText("100");
        jbZoomReset.setToolTipText("Restablecer");
        jbZoomReset.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbZoomReset.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel1.add(jbZoomReset);

        jbZoomOut.setText("−");
        jbZoomOut.setToolTipText("Alejar");
        jbZoomOut.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbZoomOut.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel1.add(jbZoomOut);

        jLabel2.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel1.add(jLabel2);

        jtfDocument.setEditable(false);
        jtfDocument.setText("folio");
        jtfDocument.setToolTipText("Folio documento");
        jtfDocument.setFocusable(false);
        jtfDocument.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel1.add(jtfDocument);

        jtfFile.setEditable(false);
        jtfFile.setText("file.pdf");
        jtfFile.setToolTipText("Archivo PDF");
        jtfFile.setFocusable(false);
        jtfFile.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(jtfFile);

        jbFileSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erp/img/icon_std_save.gif"))); // NOI18N
        jbFileSave.setToolTipText("Guardar PDF...");
        jbFileSave.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbFileSave.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel1.add(jbFileSave);

        jbFileInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erp/img/icon_std_query_doc.gif"))); // NOI18N
        jbFileInfo.setToolTipText("Ver información del PDF...");
        jbFileInfo.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbFileInfo.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel1.add(jbFileInfo);

        jbFileDeleteToUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erp/img/icon_std_return.gif"))); // NOI18N
        jbFileDeleteToUpdate.setToolTipText("Descartar para actualizar PDF...");
        jbFileDeleteToUpdate.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbFileDeleteToUpdate.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel1.add(jbFileDeleteToUpdate);

        jchkDeleteOnClose.setText("Descartar al cerrar");
        jchkDeleteOnClose.setEnabled(false);
        jchkDeleteOnClose.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel1.add(jchkDeleteOnClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton jbFileDeleteToUpdate;
    private javax.swing.JButton jbFileInfo;
    private javax.swing.JButton jbFileSave;
    private javax.swing.JButton jbGoFirstPage;
    private javax.swing.JButton jbGoLastPage;
    private javax.swing.JButton jbGoNextPage;
    private javax.swing.JButton jbGoPrevPage;
    private javax.swing.JButton jbZoomIn;
    private javax.swing.JButton jbZoomOut;
    private javax.swing.JButton jbZoomReset;
    private javax.swing.JCheckBox jchkDeleteOnClose;
    private javax.swing.JTextField jtfCurrentPage;
    private javax.swing.JTextField jtfCurrentZoom;
    private javax.swing.JTextField jtfDocument;
    private javax.swing.JTextField jtfFile;
    // End of variables declaration//GEN-END:variables

    private void initComponentsCustom() {
        SGuiUtils.setWindowBounds(this, 1000, 600);
        setResizable(true);
        
        jbSave.setEnabled(false);
        jbCancel.setEnabled(true);
        jbCancel.setText(SGuiConsts.TXT_BTN_CLOSE);
        
        addAllListeners();
    }
    
    private void showPage() {
        if (moPdf == null) {
            jtfCurrentPage.setText("");
        }
        else {
            jtfCurrentPage.setText((mnCurrentPageIndex + 1) + "/" + mnPages);
        }
    }
    
    private void showZoom() {
        if (moPdf == null) {
            jtfCurrentZoom.setText("");
        }
        else {
            jtfCurrentZoom.setText(ZOOM_OPTIONS[mnCurrentZoomIndex] + "%");
        }
    }
    
    private void showFile() {
        if (moPdf == null) {
            jtfDocument.setText("");
            jtfDocument.setToolTipText(TOOL_TIP_DOCUMENT);
            
            jtfFile.setText("");
            jtfFile.setToolTipText(TOOL_TIP_FILE);
        }
        else {
            jtfDocument.setText(moDocument.getEffectiveFolio());
            jtfDocument.setToolTipText(TOOL_TIP_DOCUMENT + ": " + jtfDocument.getText());
            
            jtfFile.setText(moPdf.getName());
            jtfFile.setToolTipText(TOOL_TIP_FILE + ": " + jtfFile.getText());
        }
    }
    
    private void renderCurrentPage() {
        try {
            SGuiUtils.setCursorWait(miClient);
            // prepare page image:

            String key = mnCurrentPageIndex + "-" + mnCurrentZoomIndex;
            BufferedImage pageImage = moPageImages.get(key);

            if (pageImage == null) {
                pageImage = moPDFRenderer.renderImage(mnCurrentPageIndex, ZOOMS[mnCurrentZoomIndex]);
                moPageImages.put(key, pageImage);
            }

            // show page:

            moLabel = new JLabel(new ImageIcon(pageImage));
            jScrollPane.getViewport().setView(moLabel);
        }
        catch (IOException ioe) {
            SLibUtils.showException(this, ioe);
        }
        finally {
            SGuiUtils.setCursorDefault(miClient);
        }
    }
    
    private void actionPerformedGoFirstPage() {
        if (mnCurrentPageIndex != 0) {
            mnCurrentPageIndex = 0;
            renderCurrentPage();
            showPage();
        }
    }
    
    private void actionPerformedGoPrevPage() {
        if (mnCurrentPageIndex > 0) {
            mnCurrentPageIndex--;
            renderCurrentPage();
            showPage();
        }
    }

    private void actionPerformedGoNextPage() {
        if (mnCurrentPageIndex < (mnPages - 1)) {
            mnCurrentPageIndex++;
            renderCurrentPage();
            showPage();
        }
    }

    private void actionPerformedGoLastPage() {
        if (mnCurrentPageIndex != (mnPages - 1)) {
            mnCurrentPageIndex = mnPages - 1;
            renderCurrentPage();
            showPage();
        }
    }

    private void actionPerformedZoomIn() {
        if (mnCurrentZoomIndex > 0) {
            mnCurrentZoomIndex--;
            renderCurrentPage();
            showZoom();
        }
    }

    private void actionPerformedZoomReset() {
        if (mnCurrentZoomIndex != ZOOM_INDEX_100) {
            mnCurrentZoomIndex = ZOOM_INDEX_100;
            renderCurrentPage();
            showZoom();
        }
    }

    private void actionPerformedZoomOut() {
        if (mnCurrentZoomIndex < (ZOOMS.length - 1)) {
            mnCurrentZoomIndex++;
            renderCurrentPage();
            showZoom();
        }
    }

    private void actionPerformedFileSave() {
        try {
            FileFilter filter = SFileUtilities.createFileNameExtensionFilter(SFileUtilities.pdf);
            JFileChooser fileChooser = miClient.getFileChooser();
            fileChooser.repaint();
            fileChooser.setAcceptAllFileFilterUsed(false);
            fileChooser.setFileFilter(filter);

            String safeFileName = moDocument.getEffectiveFolio().replaceAll("[\\\\/:*?\"<>|]", "");
            fileChooser.setSelectedFile(new File(safeFileName + "." + SFileUtilities.pdf));

            if (fileChooser.showSaveDialog(miClient.getFrame()) == JFileChooser.APPROVE_OPTION) {
                File newFile = fileChooser.getSelectedFile();

                // Ensure file ends with ".zip"
                if (!newFile.getName().toLowerCase().endsWith("." + SFileUtilities.pdf)) {
                    newFile = new File(newFile.getAbsolutePath() + "." + SFileUtilities.pdf);
                }
                
                Files.copy(
                    moPdf.toPath(),
                    newFile.toPath(),
                    StandardCopyOption.REPLACE_EXISTING
                );
                
                miClient.showMsgBoxInformation("El siguiente archivo ha sido guardado:\n" + newFile.getAbsolutePath());
            }
        }
        catch (IOException ioe) {
            SLibUtils.showException(this, ioe);
        }
        finally {
            JFileChooser fileChooser = miClient.getFileChooser();
            fileChooser.resetChoosableFileFilters();
            fileChooser.setAcceptAllFileFilterUsed(true);
        }
    }

    private void actionPerformedFileInfo() {
        try {
            BasicFileAttributes attrs = Files.readAttributes(moPdf.toPath(), BasicFileAttributes.class);
            
            String fileInfo = "Información del archivo PDF:\n\n"
                    + "Emisor documento: " + moDocument.getIssuer() + "\n"
                    + "Folio documento: " + moDocument.getEffectiveFolio() + "\n\n"
                    + "Archivo: " + moPdf.getAbsolutePath() + "\n"
                    + "Creado: " + SLibUtils.DateFormatDatetimeTimeZone.format(new Date(attrs.creationTime().toMillis())) + "\n"
                    + "Modificado: " + SLibUtils.DateFormatDatetimeTimeZone.format(new Date(attrs.lastModifiedTime().toMillis())) + "\n"
                    + "Último acceso: " + SLibUtils.DateFormatDatetimeTimeZone.format(new Date(attrs.lastAccessTime().toMillis()));
            
            miClient.showMsgBoxInformation(fileInfo);
        }
        catch (IOException ioe) {
            SLibUtils.showException(this, ioe);
        }
    }
    private void actionPerformedFileDeleteToUpdate() {
        if (!jchkDeleteOnClose.isSelected()) {
            String confirmDeletion = "¡Este archivo " + SFileUtilities.pdf.toUpperCase() + " del documento '" + moDocument.getEffectiveFolio() + "' será descartado!\n"
                    + "La próxima vez que solicite visualizarlo será descargado nuevamente desde " + SSwapConsts.SWAP_SERVICES + ".\n"
                    + SGuiConsts.MSG_CNF_CONT;
            
            if (miClient.showMsgBoxConfirm(confirmDeletion) == JOptionPane.YES_OPTION) {
                // set delete on close:
                jchkDeleteOnClose.setSelected(true);
                miClient.showMsgBoxWarning("El archivo " + SFileUtilities.pdf.toUpperCase() + " del documento '" + moDocument.getEffectiveFolio() + "' será descartado al cerrarse este diálogo.");
            }
        }
        else {
            // revert delete on close:
            jchkDeleteOnClose.setSelected(false);
            miClient.showMsgBoxInformation("El archivo " + SFileUtilities.pdf.toUpperCase() + " del documento '" + moDocument.getEffectiveFolio() + "' ya no será descartado al cerrarse este diálogo.");
        }
    }

    public void setPdf(final SDocument document, final File pdf) {
        resetForm();
        
        try {
            moDocument = document;
            moPdf = pdf;
            
            if (!moPdf.exists()) {
                miClient.showMsgBoxError("El archivo PDF no existe:\n" + moPdf.getAbsolutePath());
            }
            else {
                moPDDocument = PDDocument.load(moPdf);
                moPageImages = new HashMap<>();
                mnPages = moPDDocument.getNumberOfPages();
                
                if (mnPages < 1) {
                    miClient.showMsgBoxError("El archivo PDF no tiene páginas:\n" + moPdf.getAbsolutePath());
                }
                else {
                    moPDFRenderer = new PDFRenderer(moPDDocument);
                    mnCurrentPageIndex = 0;
                    mnCurrentZoomIndex = ZOOM_INDEX_100;

                    showPage();
                    showZoom();
                    showFile();
                    enableHandlers();
                    
                    renderCurrentPage();
                }
            }
        }
        catch (IOException ioe) {
            SLibUtils.showException(this, ioe);
        }
    }
    
    private void enableHandlers() {
        boolean enablePagination = mnPages > 1;
        jbGoFirstPage.setEnabled(enablePagination);
        jbGoPrevPage.setEnabled(enablePagination);
        jbGoNextPage.setEnabled(enablePagination);
        jbGoLastPage.setEnabled(enablePagination);
        
        boolean enableZoom = mnPages > 0 && mnCurrentPageIndex >= 0;
        jbZoomIn.setEnabled(enableZoom);
        jbZoomReset.setEnabled(enableZoom);
        jbZoomOut.setEnabled(enableZoom);
        
        boolean enableFileHandling = moPdf != null;
        jbFileSave.setEnabled(enableFileHandling);
        jbFileInfo.setEnabled(enableFileHandling);
        jbFileDeleteToUpdate.setEnabled(enableFileHandling && mbAllowDelettion);
    }
    
    @Override
    public void resetForm() {
        jScrollPane.getViewport().setView(null);
        
        moDocument = null;
        moPdf = null;
        moPDDocument = null;
        moPDFRenderer = null;
        moLabel = null;
        moPageImages = null;
        mnPages = 0;
        mnCurrentPageIndex = -1;
        mnCurrentZoomIndex = -1;
        
        jchkDeleteOnClose.setSelected(false);
        
        showPage();
        showZoom();
        showFile();
        enableHandlers();
    }
    
    @Override
    public void addAllListeners() {
        jbGoFirstPage.addActionListener(this);
        jbGoPrevPage.addActionListener(this);
        jbGoNextPage.addActionListener(this);
        jbGoLastPage.addActionListener(this);
        jbZoomIn.addActionListener(this);
        jbZoomReset.addActionListener(this);
        jbZoomOut.addActionListener(this);
        jbFileSave.addActionListener(this);
        jbFileInfo.addActionListener(this);
        jbFileDeleteToUpdate.addActionListener(this);
    }

    @Override
    public void removeAllListeners() {
        jbGoFirstPage.removeActionListener(this);
        jbGoPrevPage.removeActionListener(this);
        jbGoNextPage.removeActionListener(this);
        jbGoLastPage.removeActionListener(this);
        jbZoomIn.removeActionListener(this);
        jbZoomReset.removeActionListener(this);
        jbZoomOut.removeActionListener(this);
        jbFileSave.removeActionListener(this);
        jbFileInfo.removeActionListener(this);
        jbFileDeleteToUpdate.removeActionListener(this);
    }

    @Override
    public void reloadCatalogues() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public SDbRegistry getRegistry() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public SGuiValidation validateForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void actionCancel() {
        try {
            if (moPDDocument != null) {
                moPDDocument.close();
            }
            
            if (jchkDeleteOnClose.isSelected()) {
                Files.delete(moPdf.toPath());
            }
        }
        catch (IOException ioe) {
            SLibUtils.showException(this, ioe);
        }
        finally {
            resetForm();

            mnFormResult = SGuiConsts.FORM_RESULT_CANCEL;
            setVisible(false);
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            JButton button = (JButton) e.getSource();
            
            if (button == jbGoFirstPage) {
                actionPerformedGoFirstPage();
            }
            else if (button == jbGoPrevPage) {
                actionPerformedGoPrevPage();
            }
            else if (button == jbGoNextPage) {
                actionPerformedGoNextPage();
            }
            else if (button == jbGoLastPage) {
                actionPerformedGoLastPage();
            }
            else if (button == jbZoomIn) {
                actionPerformedZoomIn();
            }
            else if (button == jbZoomReset) {
                actionPerformedZoomReset();
            }
            else if (button == jbZoomOut) {
                actionPerformedZoomOut();
            }
            else if (button == jbFileSave) {
                actionPerformedFileSave();
            }
            else if (button == jbFileInfo) {
                actionPerformedFileInfo();
            }
            else if (button == jbFileDeleteToUpdate) {
                actionPerformedFileDeleteToUpdate();
            }
        }
    }
}
