/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package erp.mtrn.form;

import erp.client.SClientInterface;
import erp.data.SDataConstants;
import erp.data.SDataUtilities;
import erp.lib.SLibConstants;
import erp.lib.SLibUtilities;
import erp.lib.form.SFormField;
import erp.lib.form.SFormUtilities;
import erp.lib.form.SFormValidation;
import erp.mfin.data.SDataAccount;
import erp.mfin.data.SDataCostCenter;
import erp.mfin.data.SFinUtilities;
import erp.mfin.form.SPanelAccount;
import erp.mtrn.data.SDataDps;
import erp.mtrn.data.SDataDpsEntry;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Barajas
 */
public class SDialogUpdateDpsAccountCenterCost extends javax.swing.JDialog implements erp.lib.form.SFormInterface, java.awt.event.ActionListener {

    private erp.client.SClientInterface miClient;
    private int mnFormResult;
    private int mnFormStatus;
    private boolean mbFirstTime;
    private java.util.Vector<erp.lib.form.SFormField> mvFields;

    private erp.mtrn.data.SDataDps moDps;
    private erp.mtrn.data.SDataDpsEntry moDpsEntry;
    private erp.mtrn.form.SPanelDps moPanelDps;
    private erp.mfin.form.SPanelAccount moPanelAccountOldId;
    private erp.mfin.form.SPanelAccount moPanelCostCenterOldId_n;
    private erp.mfin.form.SPanelAccount moPanelAccountNewId;
    private erp.mfin.form.SPanelAccount moPanelCostCenterNewId_n;

    private SDataAccount moAccountNew;
    private SDataCostCenter moCostCenterNew;

    /** Creates new form SDialogUpdateDpsAccountCenterCost
     * @param client 
    */
    public SDialogUpdateDpsAccountCenterCost(erp.client.SClientInterface client) {
        super(client.getFrame(), true);
        miClient =  client;
        initComponents();
        initComponentsExtra();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDps = new javax.swing.JPanel();
        jlPanelDps = new javax.swing.JLabel();
        jpDpsComms = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jlItem = new javax.swing.JLabel();
        jtfItem = new javax.swing.JTextField();
        jlDummy = new javax.swing.JLabel();
        jlOriginalQuantity = new javax.swing.JLabel();
        jtfOriginalQuantity = new javax.swing.JTextField();
        jtfOriginalUnitSymbolRo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jpPanelAccountsOld = new javax.swing.JPanel();
        jlDummyAccountOld = new javax.swing.JLabel();
        jlDummyCostCenterOld_n = new javax.swing.JLabel();
        jpPanelAccountsNew = new javax.swing.JPanel();
        jlDummyAccountNew = new javax.swing.JLabel();
        jlDummyCostCenterNew_n = new javax.swing.JLabel();
        jpControls = new javax.swing.JPanel();
        jbOk = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificación de contabilización");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jpDps.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jpDps.setLayout(new java.awt.BorderLayout());

        jlPanelDps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlPanelDps.setText("[Panel de documento de compras-ventas]");
        jlPanelDps.setPreferredSize(new java.awt.Dimension(100, 200));
        jpDps.add(jlPanelDps, java.awt.BorderLayout.NORTH);

        jpDpsComms.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos adicionales:"));
        jpDpsComms.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel1.setLayout(new java.awt.GridLayout(1, 1, 5, 1));

        jPanel48.setPreferredSize(new java.awt.Dimension(108, 23));
        jPanel48.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlItem.setText("Ítem:");
        jlItem.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel48.add(jlItem);

        jtfItem.setEditable(false);
        jtfItem.setText("ITEM");
        jtfItem.setFocusable(false);
        jtfItem.setPreferredSize(new java.awt.Dimension(277, 23));
        jPanel48.add(jtfItem);

        jlDummy.setPreferredSize(new java.awt.Dimension(5, 23));
        jPanel48.add(jlDummy);

        jlOriginalQuantity.setText("Cantidad:");
        jlOriginalQuantity.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel48.add(jlOriginalQuantity);

        jtfOriginalQuantity.setEditable(false);
        jtfOriginalQuantity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfOriginalQuantity.setText("0.0000");
        jtfOriginalQuantity.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel48.add(jtfOriginalQuantity);

        jtfOriginalUnitSymbolRo.setEditable(false);
        jtfOriginalUnitSymbolRo.setText("UN");
        jtfOriginalUnitSymbolRo.setFocusable(false);
        jtfOriginalUnitSymbolRo.setPreferredSize(new java.awt.Dimension(65, 23));
        jPanel48.add(jtfOriginalUnitSymbolRo);

        jPanel1.add(jPanel48);

        jpDpsComms.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        jpPanelAccountsOld.setBorder(javax.swing.BorderFactory.createTitledBorder("Contabilización actual:"));
        jpPanelAccountsOld.setLayout(new java.awt.GridLayout(2, 1, 0, 1));

        jlDummyAccountOld.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDummyAccountOld.setText("[Panel cuenta contable actual]");
        jlDummyAccountOld.setPreferredSize(new java.awt.Dimension(100, 50));
        jpPanelAccountsOld.add(jlDummyAccountOld);

        jlDummyCostCenterOld_n.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDummyCostCenterOld_n.setText("[Panel centro costo-beneficio actual]");
        jlDummyCostCenterOld_n.setPreferredSize(new java.awt.Dimension(100, 50));
        jpPanelAccountsOld.add(jlDummyCostCenterOld_n);

        jPanel2.add(jpPanelAccountsOld);

        jpPanelAccountsNew.setBorder(javax.swing.BorderFactory.createTitledBorder("Contabilización nueva:"));
        jpPanelAccountsNew.setLayout(new java.awt.GridLayout(2, 1, 0, 1));

        jlDummyAccountNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDummyAccountNew.setText("[Panel cuenta contable nueva]");
        jlDummyAccountNew.setPreferredSize(new java.awt.Dimension(100, 50));
        jpPanelAccountsNew.add(jlDummyAccountNew);

        jlDummyCostCenterNew_n.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDummyCostCenterNew_n.setText("[Panel centro costo-beneficio nueva]");
        jlDummyCostCenterNew_n.setPreferredSize(new java.awt.Dimension(100, 50));
        jpPanelAccountsNew.add(jlDummyCostCenterNew_n);

        jPanel2.add(jpPanelAccountsNew);

        jpDpsComms.add(jPanel2, java.awt.BorderLayout.CENTER);

        jpDps.add(jpDpsComms, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpDps, java.awt.BorderLayout.CENTER);

        jpControls.setPreferredSize(new java.awt.Dimension(392, 33));
        jpControls.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jbOk.setText("Aceptar");
        jbOk.setToolTipText("[Ctrl + Enter]");
        jbOk.setPreferredSize(new java.awt.Dimension(75, 23));
        jpControls.add(jbOk);

        jbCancel.setText("Cancelar");
        jbCancel.setToolTipText("[Escape]");
        jpControls.add(jbCancel);

        getContentPane().add(jpControls, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(900, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        windowActivated();
    }//GEN-LAST:event_formWindowActivated

    private void initComponentsExtra() {
        mvFields = new java.util.Vector<erp.lib.form.SFormField>();

        try {
            moPanelDps = new SPanelDps(miClient, "");
            moPanelAccountOldId = new SPanelAccount(miClient, SDataConstants.FIN_ACC, false, true, false);
            moPanelCostCenterOldId_n = new SPanelAccount(miClient, SDataConstants.FIN_CC, false, false, false);
            moPanelAccountNewId = new SPanelAccount(miClient, SDataConstants.FIN_ACC, false, true, false);
            moPanelCostCenterNewId_n = new SPanelAccount(miClient, SDataConstants.FIN_CC, false, false, false);
        }
        catch (Exception e) {
            SLibUtilities.renderException(this, e);
        }

        jpDps.remove(jlPanelDps);
        jpDps.add(moPanelDps, BorderLayout.NORTH);
        
        jpPanelAccountsOld.remove(jlDummyAccountOld);
        jpPanelAccountsOld.remove(jlDummyCostCenterOld_n);
        jpPanelAccountsOld.add(moPanelAccountOldId);
        jpPanelAccountsOld.add(moPanelCostCenterOldId_n);
        
        jpPanelAccountsNew.remove(jlDummyAccountNew);
        jpPanelAccountsNew.remove(jlDummyCostCenterNew_n);
        jpPanelAccountsNew.add(moPanelAccountNewId);
        jpPanelAccountsNew.add(moPanelCostCenterNewId_n);

        jbOk.addActionListener(this);
        jbCancel.addActionListener(this);

        AbstractAction actionOk = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) { actionOk(); }
        };

        SFormUtilities.putActionMap(getRootPane(), actionOk, "ok", KeyEvent.VK_ENTER, KeyEvent.CTRL_DOWN_MASK);

        AbstractAction actionCancel = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) { actionCancel(); }
        };

        SFormUtilities.putActionMap(getRootPane(), actionCancel, "cancel", KeyEvent.VK_ESCAPE, 0);
    }

    private void windowActivated() {
        if (mbFirstTime) {
            mbFirstTime = false;
            moPanelAccountNewId.getFieldAccount().getComponent().requestFocus();
        }
    }
    
    private void renderItem() {
        jtfItem.setText(moDpsEntry.getDbmsItem());
        jtfOriginalQuantity.setText(miClient.getSessionXXX().getFormatters().getDecimalsQuantityFormat().format(moDpsEntry.getOriginalQuantity()));
        jtfOriginalUnitSymbolRo.setText(moDpsEntry.getDbmsOriginalUnitSymbol());
    }
    
    private void renderAccount(String account) {
        moPanelAccountOldId.getFieldAccount().setFieldValue(account);
        moPanelAccountOldId.refreshPanel();
        moPanelAccountOldId.enableFields(false);
        
        moPanelAccountNewId.getFieldAccount().setFieldValue(account);
        moPanelAccountNewId.refreshPanel();
    }
    
    private void renderCostCenter(String centerCost) {
        moPanelCostCenterOldId_n.getFieldAccount().setFieldValue(centerCost.isEmpty() ? moPanelCostCenterOldId_n.getEmptyAccountId() : centerCost);
        moPanelCostCenterOldId_n.refreshPanel();
        moPanelCostCenterOldId_n.enableFields(false);

        moPanelCostCenterNewId_n.getFieldAccount().setFieldValue(centerCost.isEmpty() ? moPanelCostCenterNewId_n.getEmptyAccountId() : centerCost);
        moPanelCostCenterNewId_n.refreshPanel();
    }

    private void actionOk() {
        SFormValidation validation = formValidate();

        if (validation.getIsError()) {
            if (validation.getComponent() != null) {
                validation.getComponent().requestFocus();
            }
            if (validation.getMessage().length() > 0) {
                miClient.showMsgBoxWarning(validation.getMessage());
            }
        }
        else {
            try {
                if (miClient.showMsgBoxConfirm("¿Esta seguro que desea modificar la contabilización actual de la partida?") == JOptionPane.OK_OPTION) {
                    mnFormResult = SLibConstants.FORM_RESULT_OK;
                    
                    SFinUtilities.updateAccountCostCenterForDpsEntry(miClient, (int[]) moDpsEntry.getPrimaryKey(), moAccountNew.getPkAccountIdXXX(), (moCostCenterNew == null ? "" : moCostCenterNew.getPkCostCenterIdXXX()));
                }
                this.setVisible(false);
            }
            catch (Exception e) {
                SLibUtilities.printOutException(this, e);
            }
        }
    }

    private void actionCancel() {
        mnFormResult = SLibConstants.FORM_RESULT_CANCEL;
        setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOk;
    private javax.swing.JLabel jlDummy;
    private javax.swing.JLabel jlDummyAccountNew;
    private javax.swing.JLabel jlDummyAccountOld;
    private javax.swing.JLabel jlDummyCostCenterNew_n;
    private javax.swing.JLabel jlDummyCostCenterOld_n;
    private javax.swing.JLabel jlItem;
    private javax.swing.JLabel jlOriginalQuantity;
    private javax.swing.JLabel jlPanelDps;
    private javax.swing.JPanel jpControls;
    private javax.swing.JPanel jpDps;
    private javax.swing.JPanel jpDpsComms;
    private javax.swing.JPanel jpPanelAccountsNew;
    private javax.swing.JPanel jpPanelAccountsOld;
    private javax.swing.JTextField jtfItem;
    private javax.swing.JTextField jtfOriginalQuantity;
    private javax.swing.JTextField jtfOriginalUnitSymbolRo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void formClearRegistry() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void formReset() {
        mnFormResult = SLibConstants.UNDEFINED;
        mnFormStatus = SLibConstants.UNDEFINED;
        mbFirstTime = true;
        moAccountNew = null;
        moCostCenterNew = null;

        moDps = null;
        moPanelDps.setDps(null, null);
        
        moPanelAccountOldId.resetPanel();
        moPanelCostCenterOldId_n.resetPanel();
        
        moPanelAccountNewId.resetPanel();
        moPanelCostCenterNewId_n.resetPanel();

        for (SFormField field : mvFields) {
            field.resetField();
        }
    }

    @Override
    public void formRefreshCatalogues() {

    }

    @Override
    public erp.lib.form.SFormValidation formValidate() {
        SDataAccount accountMajor = null;
        SFormValidation validation = new SFormValidation();
        String message = "";

        for (SFormField field : mvFields) {
            if (!field.validateField()) {
                validation.setIsError(true);
                validation.setComponent(field.getComponent());
            }
        }
            
        moAccountNew = moPanelAccountNewId.getCurrentInputAccount();
        moCostCenterNew = moPanelCostCenterNewId_n.getCurrentInputCostCenter();

        if (!validation.getIsError()) {
            // Validate account:

            message = SDataUtilities.validateAccount(miClient, moAccountNew, null);

            if (message.length() > 0) {
                validation.setMessage(message);
                validation.setComponent(moPanelAccountNewId.getFieldAccount().getComponent());
            }
            else {
                accountMajor = (SDataAccount) SDataUtilities.readRegistry((SClientInterface) miClient, SDataConstants.FIN_ACC, new Object[] { moAccountNew.getDbmsPkAccountMajorId() }, SLibConstants.EXEC_MODE_VERBOSE);
                
                if (accountMajor.getIsRequiredCostCenter() && moCostCenterNew == null) {
                    validation.setMessage("La cuenta contable ('" + moAccountNew.getAccount() + "') tiene un inconveniente:\nRequiere centro de costos y no está definido.");
                    validation.setComponent(moPanelCostCenterNewId_n.getFieldAccount().getComponent());
                }
            }
        }
        
        if (!validation.getIsError()) {
            // Validate cost center:

            if (moCostCenterNew != null) {
                message = SDataUtilities.validateCostCenter(miClient, moCostCenterNew, null);

                if (message.length() > 0) {
                    validation.setMessage(message);
                    validation.setComponent(moPanelCostCenterNewId_n.getFieldAccount().getComponent());
                }
            }
        }

        return validation;
    }

    @Override
    public void setFormStatus(int status) {
        mnFormStatus = status;
    }

    @Override
    public void setFormVisible(boolean visible) {
        setVisible(visible);
    }

    @Override
    public int getFormStatus() {
        return mnFormStatus;
    }

    @Override
    public int getFormResult() {
        return mnFormResult;
    }

    @Override
    public void setRegistry(erp.lib.data.SDataRegistry registry) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public erp.lib.data.SDataRegistry getRegistry() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void setValue(int type, java.lang.Object value) {
        switch (type) {
            case SDataConstants.TRN_DPS:
                moDps = (SDataDps) SDataUtilities.readRegistry(miClient, SDataConstants.TRN_DPS, value, SLibConstants.EXEC_MODE_VERBOSE);
                moPanelDps.setDps(moDps, null);
                break;
            case SDataConstants.TRN_DPS_ETY:
                moDpsEntry = (SDataDpsEntry) SDataUtilities.readRegistry(miClient, SDataConstants.TRN_DPS_ETY, value, SLibConstants.EXEC_MODE_VERBOSE);
                renderItem();
                break;
            case SDataConstants.FIN_ACC:
                renderAccount(((String[]) value)[0]);
                renderCostCenter(((String[]) value)[1]);
                break;
            default:
        }
    }

    @Override
    public java.lang.Object getValue(int type) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public javax.swing.JLabel getTimeoutLabel() {
        return null;
    }

    @Override
    public void actionPerformed(java.awt.event.ActionEvent e) {
        if (e.getSource() instanceof javax.swing.JButton) {
            JButton button = (JButton) e.getSource();

            if (button == jbOk) {
                actionOk();
            }
            else if (button == jbCancel) {
                actionCancel();
            }
        }
    }
}
