/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package erp.mtrn.form;

import erp.data.SDataConstants;
import erp.data.SDataConstantsSys;
import erp.data.SDataUtilities;
import erp.lib.SLibConstants;
import erp.lib.SLibUtilities;
import erp.lib.form.SFormField;
import erp.lib.form.SFormUtilities;
import erp.lib.form.SFormValidation;
import erp.mod.trn.utils.SStockValuationUtils;
import erp.mtrn.data.SDataDps;
import erp.mtrn.data.SDataDpsEntry;
import erp.mtrn.data.STrnUtilities;
import static erp.mtrn.data.STrnUtilities.isServiceOrder;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import sa.lib.gui.SGuiConsts;

/**
 *
 * @author Claudio Peña, Rodrigo Ayala
 */
public class SDialogUpdateDpsItemRefConcept extends javax.swing.JDialog implements erp.lib.form.SFormInterface, java.awt.event.ActionListener, java.awt.event.ItemListener {
    
    public static final int CONCEPT_LENGTH_MAX = 130;
    
    private erp.client.SClientInterface miClient;
    private int mnFormResult;
    private int mnFormStatus;
    private int mnRegistryType;
    private boolean mbFirstTime;
    private java.util.Vector<erp.lib.form.SFormField> mvFields;

    private erp.mtrn.data.SDataDps moDps;
    private erp.mtrn.data.SDataDpsEntry moDpsEntry;
    private erp.mtrn.form.SPanelDps moPanelDps;
    private erp.lib.form.SFormField moFieldConceptKey;
    private erp.lib.form.SFormField moFieldConcept;

    
    private erp.lib.form.SFormField moFieldPkItemId;
    /** Creates new form SDialogUpdateDpsAccountCenterCost
     * @param client 
    */
    public SDialogUpdateDpsItemRefConcept(erp.client.SClientInterface client) {
        super(client.getFrame(), true);
        miClient = client;
        initComponents();
        initComponentsExtra();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDps = new javax.swing.JPanel();
        jlPanelDps = new javax.swing.JLabel();
        jpDpsComms = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jlItem = new javax.swing.JLabel();
        jtfItem = new javax.swing.JTextField();
        jlDummy = new javax.swing.JLabel();
        jlOriginalQuantity = new javax.swing.JLabel();
        jtfOriginalQuantity = new javax.swing.JTextField();
        jtfOriginalUnitSymbolRo = new javax.swing.JTextField();
        jPanel49 = new javax.swing.JPanel();
        jlIConceptfKeyOld = new javax.swing.JLabel();
        jtfConceptfKeyOld = new javax.swing.JTextField();
        jlDummy3 = new javax.swing.JLabel();
        jlConceptfKeyNew = new javax.swing.JLabel();
        jtfConceptKeyNew = new javax.swing.JTextField();
        jPanel50 = new javax.swing.JPanel();
        jlItemConceptOld = new javax.swing.JLabel();
        jtfItemConceptOld = new javax.swing.JTextField();
        jlDummy2 = new javax.swing.JLabel();
        jlItemConceptNew = new javax.swing.JLabel();
        jtfItemConceptNew = new javax.swing.JTextField();
        jPanel51 = new javax.swing.JPanel();
        jlItemRefOld = new javax.swing.JLabel();
        jtfItemRefOld = new javax.swing.JTextField();
        jlDummy1 = new javax.swing.JLabel();
        jlItemRefNew = new javax.swing.JLabel();
        jcbFkItemId = new javax.swing.JComboBox();
        jbFkItemId = new javax.swing.JButton();
        jpControls = new javax.swing.JPanel();
        jbOk = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificación de contabilización");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jpDps.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jpDps.setLayout(new java.awt.BorderLayout());

        jlPanelDps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlPanelDps.setText("[Panel de documento de compras-ventas]");
        jlPanelDps.setPreferredSize(new java.awt.Dimension(100, 200));
        jpDps.add(jlPanelDps, java.awt.BorderLayout.NORTH);

        jpDpsComms.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos adicionales:"));
        jpDpsComms.setLayout(new java.awt.BorderLayout(0, 1));

        jPanel1.setPreferredSize(new java.awt.Dimension(108, 150));
        jPanel1.setLayout(new java.awt.GridLayout(5, 1, 5, 1));

        jPanel48.setPreferredSize(new java.awt.Dimension(108, 23));
        jPanel48.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlItem.setText("Ítem:");
        jlItem.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel48.add(jlItem);

        jtfItem.setEditable(false);
        jtfItem.setText("ITEM");
        jtfItem.setFocusable(false);
        jtfItem.setPreferredSize(new java.awt.Dimension(277, 23));
        jPanel48.add(jtfItem);

        jlDummy.setPreferredSize(new java.awt.Dimension(5, 23));
        jPanel48.add(jlDummy);

        jlOriginalQuantity.setText("Cantidad:");
        jlOriginalQuantity.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel48.add(jlOriginalQuantity);

        jtfOriginalQuantity.setEditable(false);
        jtfOriginalQuantity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfOriginalQuantity.setText("0.0000");
        jtfOriginalQuantity.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel48.add(jtfOriginalQuantity);

        jtfOriginalUnitSymbolRo.setEditable(false);
        jtfOriginalUnitSymbolRo.setText("UN");
        jtfOriginalUnitSymbolRo.setFocusable(false);
        jtfOriginalUnitSymbolRo.setPreferredSize(new java.awt.Dimension(65, 23));
        jPanel48.add(jtfOriginalUnitSymbolRo);

        jPanel1.add(jPanel48);

        jPanel49.setPreferredSize(new java.awt.Dimension(108, 23));
        jPanel49.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlIConceptfKeyOld.setText("Clave actual:");
        jlIConceptfKeyOld.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel49.add(jlIConceptfKeyOld);

        jtfConceptfKeyOld.setEditable(false);
        jtfConceptfKeyOld.setText("CLAVE ACTUAL");
        jtfConceptfKeyOld.setFocusable(false);
        jtfConceptfKeyOld.setPreferredSize(new java.awt.Dimension(277, 23));
        jPanel49.add(jtfConceptfKeyOld);

        jlDummy3.setPreferredSize(new java.awt.Dimension(5, 23));
        jPanel49.add(jlDummy3);

        jlConceptfKeyNew.setText("Clave nueva:");
        jlConceptfKeyNew.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel49.add(jlConceptfKeyNew);

        jtfConceptKeyNew.setEditable(false);
        jtfConceptKeyNew.setFocusable(false);
        jtfConceptKeyNew.setPreferredSize(new java.awt.Dimension(260, 23));
        jPanel49.add(jtfConceptKeyNew);

        jPanel1.add(jPanel49);

        jPanel50.setPreferredSize(new java.awt.Dimension(108, 23));
        jPanel50.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlItemConceptOld.setText("Concepto actual:");
        jlItemConceptOld.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel50.add(jlItemConceptOld);

        jtfItemConceptOld.setEditable(false);
        jtfItemConceptOld.setText("CONCEPTO ACTUAL");
        jtfItemConceptOld.setFocusable(false);
        jtfItemConceptOld.setPreferredSize(new java.awt.Dimension(277, 23));
        jPanel50.add(jtfItemConceptOld);

        jlDummy2.setPreferredSize(new java.awt.Dimension(5, 23));
        jPanel50.add(jlDummy2);

        jlItemConceptNew.setText("Concepto nuevo:");
        jlItemConceptNew.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel50.add(jlItemConceptNew);

        jtfItemConceptNew.setEditable(false);
        jtfItemConceptNew.setFocusable(false);
        jtfItemConceptNew.setPreferredSize(new java.awt.Dimension(260, 23));
        jPanel50.add(jtfItemConceptNew);

        jPanel1.add(jPanel50);

        jPanel51.setPreferredSize(new java.awt.Dimension(108, 23));
        jPanel51.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlItemRefOld.setText("Ítem referencia actual:");
        jlItemRefOld.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel51.add(jlItemRefOld);

        jtfItemRefOld.setEditable(false);
        jtfItemRefOld.setText("ITEM REFERENCIA ACTUAL");
        jtfItemRefOld.setFocusable(false);
        jtfItemRefOld.setPreferredSize(new java.awt.Dimension(277, 23));
        jPanel51.add(jtfItemRefOld);

        jlDummy1.setPreferredSize(new java.awt.Dimension(5, 23));
        jPanel51.add(jlDummy1);

        jlItemRefNew.setText("Ítem referencia nuevo:");
        jlItemRefNew.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel51.add(jlItemRefNew);

        jcbFkItemId.setMaximumRowCount(16);
        jcbFkItemId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbFkItemId.setPreferredSize(new java.awt.Dimension(240, 23));
        jPanel51.add(jcbFkItemId);

        jbFkItemId.setText("...");
        jbFkItemId.setToolTipText("Seleccionar ítem");
        jbFkItemId.setFocusable(false);
        jbFkItemId.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel51.add(jbFkItemId);

        jPanel1.add(jPanel51);

        jpDpsComms.add(jPanel1, java.awt.BorderLayout.NORTH);

        jpDps.add(jpDpsComms, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpDps, java.awt.BorderLayout.CENTER);

        jpControls.setPreferredSize(new java.awt.Dimension(392, 33));
        jpControls.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jbOk.setText("Aceptar");
        jbOk.setToolTipText("[Ctrl + Enter]");
        jbOk.setPreferredSize(new java.awt.Dimension(75, 23));
        jpControls.add(jbOk);

        jbCancel.setText("Cancelar");
        jbCancel.setToolTipText("[Escape]");
        jpControls.add(jbCancel);

        getContentPane().add(jpControls, java.awt.BorderLayout.PAGE_END);

        getAccessibleContext().setAccessibleName("Modificación de item referencia y conceptos ");

        setSize(new java.awt.Dimension(900, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        windowActivated();
    }//GEN-LAST:event_formWindowActivated

    private void initComponentsExtra() {
        mvFields = new java.util.Vector<>();
        
        moFieldPkItemId = new SFormField(miClient, SLibConstants.DATA_TYPE_KEY, true, jcbFkItemId, jlItemRefNew);
        moFieldPkItemId.setPickerButton(jbFkItemId);
        moFieldConceptKey = new SFormField(miClient, SLibConstants.DATA_TYPE_STRING, true, jtfConceptKeyNew, jlConceptfKeyNew);
        moFieldConceptKey.setLengthMax(35);
        moFieldConcept = new SFormField(miClient, SLibConstants.DATA_TYPE_STRING, true, jtfItemConceptNew, jlItemConceptNew);
        moFieldConcept.setLengthMax(CONCEPT_LENGTH_MAX);
         
        try {
            moPanelDps = new SPanelDps(miClient, "");
        }
        catch (Exception e) {
            SLibUtilities.renderException(this, e);
        }
        jtfConceptKeyNew.setToolTipText(null);
        jtfConceptKeyNew.setEditable(true);
        jtfConceptKeyNew.setFocusable(true);
        jtfConceptKeyNew.setCaretPosition(0);
        
        jtfItemConceptNew.setToolTipText(null);
        jtfItemConceptNew.setEditable(true);
        jtfItemConceptNew.setFocusable(true);
        jtfItemConceptNew.setCaretPosition(0);
        
        jpDps.remove(jlPanelDps);
        jpDps.add(moPanelDps, BorderLayout.NORTH);
        
        jbOk.addActionListener(this);
        jbCancel.addActionListener(this);
        jbFkItemId.addActionListener(this);
                
        AbstractAction actionOk = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) { actionOk(); }
        };

        SFormUtilities.putActionMap(getRootPane(), actionOk, "ok", KeyEvent.VK_ENTER, KeyEvent.CTRL_DOWN_MASK);

        AbstractAction actionCancel = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) { actionCancel(); }
        };

        SFormUtilities.putActionMap(getRootPane(), actionCancel, "cancel", KeyEvent.VK_ESCAPE, 0);
    }

    private void windowActivated() {
        if (mbFirstTime) {
            mbFirstTime = false;
        }
    }
    
    private void renderItem() {
        jtfItem.setText(moDpsEntry.getDbmsItem());
        jtfItem.setCaretPosition(0);
        jtfOriginalQuantity.setText(miClient.getSessionXXX().getFormatters().getDecimalsQuantityFormat().format(moDpsEntry.getOriginalQuantity()));
        jtfOriginalUnitSymbolRo.setText(moDpsEntry.getDbmsOriginalUnitSymbol());
        
        jtfConceptfKeyOld.setText(moDpsEntry.getConceptKey());
        jtfItemConceptOld.setText(moDpsEntry.getConcept());
        jtfItemRefOld.setText(moDpsEntry.getDbmsItemRef_n());
    }


    private void actionOk() {
        SFormValidation validation = formValidate();

        if (validation.getIsError()) {
            if (validation.getComponent() != null) {
                validation.getComponent().requestFocus();
            }
            if (validation.getMessage().length() > 0) {
                miClient.showMsgBoxWarning(validation.getMessage());
            }
        }
        else {
            try {
                if (miClient.showMsgBoxConfirm("¿Esta seguro que desea modificar los valores actuales de la partida? \n Esta función es solo para órdenes de compra.") == JOptionPane.OK_OPTION) {
                    if (!aceptDocumentsParentsChanges() || !acceptStockValuationChanges()) {
                        return;
                    }
                    
                    if(!isServiceOrder(miClient, moDps.getFkSourceYearId_n(), moDps.getFkSourceDocId_n())) {
                        if (((!jtfConceptKeyNew.getText().isEmpty()) || (!jtfItemConceptNew.getText().isEmpty()) || jcbFkItemId.getSelectedIndex() > 0)) {
                            String conceptKeyNew = moFieldConceptKey.getString();
                            String conceptNew = moFieldConcept.getString();
                            int itemRef = (Integer) (moFieldPkItemId.getKeyAsIntArray())[0];
                                    
                            if ((STrnUtilities.requieredItemGen(miClient, moDpsEntry.getFkItemId()) && itemRef <= 0 )) {
                                miClient.showMsgBoxWarning("El ítem '" + moDpsEntry.getDbmsItem() + "' requiere un ítem de refencia." );
                                return;
                            }
                            else {
                                STrnUtilities.updateItemRefInvoice(miClient.getSession().getStatement().getConnection(), miClient, moDps.getPkYearId(), moDps.getPkDocId(), moDpsEntry ,conceptKeyNew, conceptNew, itemRef);
                            }  
                        }
                        else {
                            miClient.showMsgBoxInformation("No se modificó ningún campo para el reglón." );
                            return;
                        }
                        mnFormResult = SLibConstants.FORM_RESULT_OK;
                    }
                    else {
                        miClient.showMsgBoxInformation("Esta factura corresponde a una orden de servicios.");
                        this.setVisible(false);
                        }
                    miClient.showMsgBoxInformation("El proceso ha terminado.");
                    mnFormResult = SGuiConsts.FORM_RESULT_OK;
                    dispose();
                    }
                }
            catch (Exception e) {
                SLibUtilities.renderException(this, e); //print out exception was changed to render Exception, to show message to user
            }
        }
    }

    private void actionCancel() {
        mnFormResult = SLibConstants.FORM_RESULT_CANCEL;
        setVisible(false);
    }

    private boolean acceptStockValuationChanges() {
        try {
            int count = SStockValuationUtils.countStockValuationsForDpsEntry(
                    miClient.getSession(),
                    new int[] {
                        moDpsEntry.getPkYearId(),
                        moDpsEntry.getPkDocId(),
                        moDpsEntry.getPkEntryId()
                    },
                    false // factura
            );

            if (count > 0) {
                int option = JOptionPane.showConfirmDialog(
                        this,
                        "La partida tiene " + count + " valuación(es) de inventario asociada(s).\n\n"
                        + "¿Desea continuar con los cambios?",
                        "Confirmar cambios con valuaciones",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

                return option == JOptionPane.OK_OPTION;
            }
        }
        catch (Exception e) {
            SLibUtilities.renderException(this, e);
            return false;
        }

        return true;
    }
    
    private boolean aceptDocumentsParentsChanges(){
        String affectedEntries = getModifiedEntriesWithParents();
        
        if (!affectedEntries.isEmpty()) {
            int option = JOptionPane.showConfirmDialog(
                    this,
                    "La partida tiene documentos vinculados que también se verán afectados:\n\n"
                        + affectedEntries
                        + "\n ¿Desea continuar con los cambios?",
                    "Confirmar cambios",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            
            return option == JOptionPane.OK_OPTION;
        }
        
        return true;
    }

    private String getModifiedEntriesWithParents() {
        StringBuilder message = new StringBuilder();

        try {
            int[] entryKey = (int[]) moDpsEntry.getPrimaryKey();

            String sql = "SELECT "
                    + "d.fid_ct_dps AS rel_ct_dps, "
                    + "d.fid_cl_dps AS rel_cl_dps, "
                    + "d.fid_tp_dps AS rel_tp_dps, "
                    + "CONCAT(d.num_ser, '-', d.num) AS rel_folio, "
                    + "s.id_src_ety AS rel_ety, "
                    + "0 AS is_mat_req "
                    + "FROM trn_dps_dps_supply AS s "
                    + "INNER JOIN trn_dps AS d ON "
                    + "s.id_src_year = d.id_year "
                    + "AND s.id_src_doc = d.id_doc "
                    + "WHERE s.id_des_year = " + entryKey[0] + " "
                    + "AND s.id_des_doc = " + entryKey[1] + " "
                    + "AND s.id_des_ety = " + entryKey[2] + " "

                    + "UNION ALL "

                    + "SELECT "
                    + "0 AS rel_ct_dps, "
                    + "0 AS rel_cl_dps, "
                    + "0 AS rel_tp_dps, " 
                    + "mr.num AS rel_folio, "
                    + "mrq.fid_mat_req_ety AS rel_ety, "
                    + "1 AS is_mat_req "
                    + "FROM trn_dps_mat_req AS mrq "
                    + "INNER JOIN trn_mat_req AS mr ON "
                    + "mrq.fid_mat_req = mr.id_mat_req "
                    + "WHERE mrq.fid_dps_year = " + entryKey[0] + " "
                    + "AND mrq.fid_dps_doc = " + entryKey[1] + " "
                    + "AND mrq.fid_dps_ety = " + entryKey[2] + " "
            
                    + "UNION ALL "
                    
                    + "SELECT "
                    + "d.fid_ct_dps AS rel_ct_dps, "
                    + "d.fid_cl_dps AS rel_cl_dps, "
                    + "d.fid_tp_dps AS rel_tp_dps, "
                    + "CONCAT(d.num_ser, '-', d.num) AS rel_folio, "
                    + "a.id_adj_ety AS rel_ety, "
                    + "0 AS is_mat_req "
                    + "FROM trn_dps_dps_adj AS a "
                    + "INNER JOIN trn_dps AS d ON "
                    + "a.id_adj_year = d.id_year "
                    + "AND a.id_adj_doc = d.id_doc "
                    + "WHERE a.id_dps_year = " + entryKey[0] + " "
                    + "AND a.id_dps_doc = " + entryKey[1] + " "
                    + "AND a.id_dps_ety = " + entryKey[2];
                    
            java.sql.ResultSet rs = miClient.getSession().getStatement().executeQuery(sql);

            while (rs.next()) {
                String docType;

                if (rs.getBoolean("is_mat_req")) {
                    docType = "Requisición";
                }
                else {
                    switch (rs.getInt("rel_cl_dps")) {
                        case SDataConstantsSys.TRNS_CL_DPS_EST:
                            docType = "Cotización";
                            break;

                        case SDataConstantsSys.TRNS_CL_DPS_ORD:
                            docType = "Pedido";
                            break;

                        case SDataConstantsSys.TRNS_CL_DPS_DOC:
                            int tpDps = rs.getInt("rel_tp_dps");
                            
                            if (tpDps == SDataConstantsSys.TRNU_TP_DPS_PUR_INV[2] || tpDps == SDataConstantsSys.TRNU_TP_DPS_SAL_INV[2]) {
                                docType = "Factura";
                            } 
                            else if (tpDps == SDataConstantsSys.TRNU_TP_DPS_PUR_REM[2] || tpDps == SDataConstantsSys.TRNU_TP_DPS_SAL_REM[2]) {
                                docType = "Remisión";
                            } 
                            else if (tpDps == SDataConstantsSys.TRNU_TP_DPS_PUR_REC[2] || tpDps == SDataConstantsSys.TRNU_TP_DPS_SAL_REC[2]) {
                                docType = "Nota Venta";
                            } 
                            else if (tpDps == SDataConstantsSys.TRNU_TP_DPS_PUR_TIC[2] || tpDps == SDataConstantsSys.TRNU_TP_DPS_SAL_TIC[2]) {
                                docType = "Ticket";
                            } 
                            else {
                                docType = "Documento"; // Fallback por si acaso
                            }
                            break;
                        
                        case SDataConstantsSys.TRNS_CL_DPS_ADJ:
                            docType = "Ajuste / NC";
                            break;

                        default:
                            docType = "Documento";
                    }
                }
                
                message.append("Partida #")
                        .append(entryKey[2])
                        .append(" ← ")
                        .append(docType)
                        .append(" ")
                        .append(rs.getString("rel_folio"))
                        .append(" (partida #")
                        .append(rs.getInt("rel_ety"))
                        .append(")\n");
            }

            rs.close();
        }
        catch (Exception e) {
            SLibUtilities.printOutException(this, e);
        }

        return message.toString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbFkItemId;
    private javax.swing.JButton jbOk;
    private javax.swing.JComboBox jcbFkItemId;
    private javax.swing.JLabel jlConceptfKeyNew;
    private javax.swing.JLabel jlDummy;
    private javax.swing.JLabel jlDummy1;
    private javax.swing.JLabel jlDummy2;
    private javax.swing.JLabel jlDummy3;
    private javax.swing.JLabel jlIConceptfKeyOld;
    private javax.swing.JLabel jlItem;
    private javax.swing.JLabel jlItemConceptNew;
    private javax.swing.JLabel jlItemConceptOld;
    private javax.swing.JLabel jlItemRefNew;
    private javax.swing.JLabel jlItemRefOld;
    private javax.swing.JLabel jlOriginalQuantity;
    private javax.swing.JLabel jlPanelDps;
    private javax.swing.JPanel jpControls;
    private javax.swing.JPanel jpDps;
    private javax.swing.JPanel jpDpsComms;
    private javax.swing.JTextField jtfConceptKeyNew;
    private javax.swing.JTextField jtfConceptfKeyOld;
    private javax.swing.JTextField jtfItem;
    private javax.swing.JTextField jtfItemConceptNew;
    private javax.swing.JTextField jtfItemConceptOld;
    private javax.swing.JTextField jtfItemRefOld;
    private javax.swing.JTextField jtfOriginalQuantity;
    private javax.swing.JTextField jtfOriginalUnitSymbolRo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void formClearRegistry() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    @SuppressWarnings("unchecked")
    public void formReset() {
        mnFormResult = SLibConstants.UNDEFINED;
        mnFormStatus = SLibConstants.UNDEFINED;
        mbFirstTime = true;

        moDps = null;
        moPanelDps.setDps(null, null);
        moFieldConcept.resetField();
        moFieldPkItemId.resetField();
        jtfConceptKeyNew.setText("");
        jtfItemConceptNew.setText("");
                
        for (SFormField field : mvFields) {
            field.resetField();
        }
        SFormUtilities.populateComboBox(miClient, jcbFkItemId, SDataConstants.ITMU_ITEM);

    }

    @Override
    @SuppressWarnings("unchecked")
    public void formRefreshCatalogues() {
          SFormUtilities.populateComboBox(miClient, jcbFkItemId, SDataConstants.ITMU_ITEM);

    }

    @Override
    public erp.lib.form.SFormValidation formValidate() {
        SFormValidation validation = new SFormValidation();

        for (SFormField field : mvFields) {
            if (!field.validateField()) {
                validation.setIsError(true);
                validation.setComponent(field.getComponent());
            }
        }

        if (!validation.getIsError()) {
            if (jcbFkItemId.getSelectedIndex() > 0) {
                if ((int) moFieldPkItemId.getKeyAsIntArray()[0] == moDpsEntry.getFkItemRefId_n()) {
                    validation.setMessage(SLibConstants.MSG_ERR_GUI_FIELD_VALUE_DIF + "'" + jlItemRefNew.getText() + "'.");
                    validation.setComponent(jcbFkItemId);
                    validation.setIsError(true);
                }
            }
        }
        
        return validation;
    }

    @Override
    public void setFormStatus(int status) {
        mnFormStatus = status;
    }

    @Override
    public void setFormVisible(boolean visible) {
        setVisible(visible);
    }

    @Override
    public int getFormStatus() {
        return mnFormStatus;
    }

    @Override
    public int getFormResult() {
        return mnFormResult;
    }

    @Override
    public void setRegistry(erp.lib.data.SDataRegistry registry) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public erp.lib.data.SDataRegistry getRegistry() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void setValue(int type, java.lang.Object value) {
        switch (type) {
            case SDataConstants.TRN_DPS:
                moDps = (SDataDps) SDataUtilities.readRegistry(miClient, SDataConstants.TRN_DPS, value, SLibConstants.EXEC_MODE_VERBOSE);
                moPanelDps.setDps(moDps, null);
                break;
            case SDataConstants.TRN_DPS_ETY:
                moDpsEntry = (SDataDpsEntry) SDataUtilities.readRegistry(miClient, SDataConstants.TRN_DPS_ETY, value, SLibConstants.EXEC_MODE_VERBOSE);
                renderItem();
                break;
            default:
        }
    }

    public void setRegistryType(int registryType){
        mnRegistryType = registryType;
    }
    
    @Override
    public java.lang.Object getValue(int type) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public javax.swing.JLabel getTimeoutLabel() {
        return null;
    }

    
    private void actionFkItemId() {
        if (miClient.pickOption(SDataConstants.ITMX_ITEM_IOG, moFieldPkItemId, SDataConstantsSys.ITMS_CL_ITEM_EXP_MFG) == SLibConstants.FORM_RESULT_OK) {
            itemStateChangedPkLinkTypeId();
        }
    }
    
    private void itemStateChangedPkLinkTypeId() {
        boolean enable = true;
    }

    @Override
    public void actionPerformed(java.awt.event.ActionEvent e) {
        if (e.getSource() instanceof javax.swing.JButton) {
            JButton button = (JButton) e.getSource();

            if (button == jbOk) {
                actionOk();
            }
            else if (button == jbCancel) {
                actionCancel();
            }
            else if (button == jbFkItemId) {
                actionFkItemId();
            }
        }
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource() instanceof javax.swing.JComboBox && e.getStateChange() == ItemEvent.SELECTED) {
            JComboBox comboBox = (JComboBox)  e.getSource();
        }
    }    
}
