
package erp.mtrn.form;

import erp.data.SDataConstants;
import erp.data.SDataReadDescriptions;
import erp.data.SDataUtilities;
import erp.lib.SLibConstants;
import erp.lib.SLibUtilities;
import erp.mod.cfg.utils.SAuthorizationUtils;
import erp.mod.trn.db.SDbMaterialRequest;
import erp.musr.data.SDataUser;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Edwin Carmona
 */
public class SPanelMaterialRequest extends javax.swing.JPanel {

    private erp.client.SClientInterface miClient;
    private java.lang.String msTitledBorderComplement;
    private SDbMaterialRequest moMaterialRequest;

    /** Creates new form SPanelDps */
    public SPanelMaterialRequest(erp.client.SClientInterface client) {
        this(client, "");
    }

    /** Creates new form SPanelDps */
    public SPanelMaterialRequest(erp.client.SClientInterface client, java.lang.String titledBorderComplement) {
        miClient = client;
        msTitledBorderComplement = titledBorderComplement;

        initComponents();
        initComponentsExtra();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDps = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jlDpsType = new javax.swing.JLabel();
        jtfDocumentType = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jlProviderEntity = new javax.swing.JLabel();
        jtfProviderEntity = new javax.swing.JTextField();
        jPanel62 = new javax.swing.JPanel();
        jlUserCreator = new javax.swing.JLabel();
        jtfUser = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jlDate = new javax.swing.JLabel();
        jtfDate = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jlNumber = new javax.swing.JLabel();
        jtfNumber = new javax.swing.JTextField();
        jckIsAuthorized = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jlCurrency = new javax.swing.JLabel();
        jtfCurrency = new javax.swing.JTextField();
        jtfExchangeRate = new javax.swing.JTextField();
        jpDpsValue = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jlSubtotalCy_r = new javax.swing.JLabel();
        jtfSubtotalCy_r = new javax.swing.JTextField();
        jtfSubtotalCy_rCurKey = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jlTotalCy_r = new javax.swing.JLabel();
        jtfTotalCy_r = new javax.swing.JTextField();
        jtfTotalCy_rCurKey = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jlTaxRetainedCy_r = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jlConsumeEntity = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jtfConsumeEntity = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jpDps.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del documento:"));
        jpDps.setLayout(new java.awt.GridLayout(6, 1, 0, 1));

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlDpsType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlDpsType.setText("Tipo de documento:");
        jlDpsType.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel6.add(jlDpsType);

        jtfDocumentType.setEditable(false);
        jtfDocumentType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfDocumentType.setText("DOCUMENT TYPE");
        jtfDocumentType.setFocusable(false);
        jtfDocumentType.setPreferredSize(new java.awt.Dimension(250, 23));
        jPanel6.add(jtfDocumentType);

        jpDps.add(jPanel6);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlProviderEntity.setText("Centro de suministro:");
        jlProviderEntity.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel12.add(jlProviderEntity);

        jtfProviderEntity.setEditable(false);
        jtfProviderEntity.setText("PROVIDER ENTITY");
        jtfProviderEntity.setFocusable(false);
        jtfProviderEntity.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel12.add(jtfProviderEntity);

        jpDps.add(jPanel12);

        jPanel62.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlUserCreator.setText("Usuario:");
        jlUserCreator.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel62.add(jlUserCreator);

        jtfUser.setEditable(false);
        jtfUser.setText("ABC000ABC000");
        jtfUser.setFocusable(false);
        jtfUser.setPreferredSize(new java.awt.Dimension(152, 23));
        jPanel62.add(jtfUser);

        jpDps.add(jPanel62);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlDate.setText("Fecha:");
        jlDate.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel11.add(jlDate);

        jtfDate.setEditable(false);
        jtfDate.setText("dd/mm/yyyy");
        jtfDate.setFocusable(false);
        jtfDate.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel11.add(jtfDate);

        jpDps.add(jPanel11);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlNumber.setText("Folio requisición:");
        jlNumber.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel16.add(jlNumber);

        jtfNumber.setEditable(false);
        jtfNumber.setText("000000000");
        jtfNumber.setFocusable(false);
        jtfNumber.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel16.add(jtfNumber);

        jckIsAuthorized.setText("Autorizado");
        jckIsAuthorized.setEnabled(false);
        jckIsAuthorized.setPreferredSize(new java.awt.Dimension(95, 23));
        jPanel16.add(jckIsAuthorized);

        jpDps.add(jPanel16);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlCurrency.setText("Moneda y tipo de cambio:");
        jlCurrency.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel2.add(jlCurrency);

        jtfCurrency.setEditable(false);
        jtfCurrency.setText("CURRENCY");
        jtfCurrency.setFocusable(false);
        jtfCurrency.setPreferredSize(new java.awt.Dimension(152, 23));
        jPanel2.add(jtfCurrency);

        jtfExchangeRate.setEditable(false);
        jtfExchangeRate.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfExchangeRate.setText("0.0000");
        jtfExchangeRate.setFocusable(false);
        jtfExchangeRate.setPreferredSize(new java.awt.Dimension(95, 23));
        jPanel2.add(jtfExchangeRate);

        jpDps.add(jPanel2);

        add(jpDps, java.awt.BorderLayout.WEST);

        jpDpsValue.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor del documento:"));
        jpDpsValue.setLayout(new java.awt.GridLayout(6, 1, 0, 1));

        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlSubtotalCy_r.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlSubtotalCy_r.setText("Subtotal:");
        jlSubtotalCy_r.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel19.add(jlSubtotalCy_r);

        jtfSubtotalCy_r.setEditable(false);
        jtfSubtotalCy_r.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfSubtotalCy_r.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfSubtotalCy_r.setText("0,000,000,000.00");
        jtfSubtotalCy_r.setFocusable(false);
        jtfSubtotalCy_r.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel19.add(jtfSubtotalCy_r);

        jtfSubtotalCy_rCurKey.setEditable(false);
        jtfSubtotalCy_rCurKey.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfSubtotalCy_rCurKey.setText("CUR");
        jtfSubtotalCy_rCurKey.setFocusable(false);
        jtfSubtotalCy_rCurKey.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel19.add(jtfSubtotalCy_rCurKey);

        jpDpsValue.add(jPanel19);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlTotalCy_r.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlTotalCy_r.setText("Total:");
        jlTotalCy_r.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel9.add(jlTotalCy_r);

        jtfTotalCy_r.setEditable(false);
        jtfTotalCy_r.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfTotalCy_r.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfTotalCy_r.setText("0,000,000,000.00");
        jtfTotalCy_r.setFocusable(false);
        jtfTotalCy_r.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel9.add(jtfTotalCy_r);

        jtfTotalCy_rCurKey.setEditable(false);
        jtfTotalCy_rCurKey.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfTotalCy_rCurKey.setText("CUR");
        jtfTotalCy_rCurKey.setFocusable(false);
        jtfTotalCy_rCurKey.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel9.add(jtfTotalCy_rCurKey);

        jpDpsValue.add(jPanel9);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlTaxRetainedCy_r.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel14.add(jlTaxRetainedCy_r);

        jpDpsValue.add(jPanel14);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jlConsumeEntity.setText("Centro de consumo:");
        jlConsumeEntity.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel7.add(jlConsumeEntity);

        jpDpsValue.add(jPanel7);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));

        jtfConsumeEntity.setEditable(false);
        jtfConsumeEntity.setText("CONSUME ENTITY");
        jtfConsumeEntity.setFocusable(false);
        jtfConsumeEntity.setPreferredSize(new java.awt.Dimension(385, 23));
        jPanel13.add(jtfConsumeEntity);

        jpDpsValue.add(jPanel13);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0));
        jpDpsValue.add(jPanel1);

        add(jpDpsValue, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsExtra() {
        setMaterialRequest(null);

        if (msTitledBorderComplement.length() > 0) {
            ((TitledBorder) jpDps.getBorder()).setTitle(SLibUtilities.textTrim("Datos del documento " + msTitledBorderComplement) + ":");
            ((TitledBorder) jpDpsValue.getBorder()).setTitle(SLibUtilities.textTrim("Valor del documento " + msTitledBorderComplement) + ":");
        }
    }

    private void renderMaterialRequest() {
        jtfDocumentType.setText("REQUISICIÓN DE MATERIALES");
        jtfDocumentType.setToolTipText(jtfDocumentType.getText());
        jtfDocumentType.setCaretPosition(0);
        
        if (moMaterialRequest == null) {
            jtfProviderEntity.setText("");
            jtfConsumeEntity.setText("");

            jtfProviderEntity.setToolTipText(null);
            jtfConsumeEntity.setToolTipText(null);

            jtfDate.setText("");
            jtfNumber.setText("");
            jtfUser.setText("");
            jtfCurrency.setText("");
            jtfExchangeRate.setText("");

            jtfSubtotalCy_r.setText("");
            jtfTotalCy_r.setText("");

            jtfSubtotalCy_rCurKey.setText("");
            jtfTotalCy_rCurKey.setText("");

            jckIsAuthorized.setSelected(false);
        }
        else {
            jtfProviderEntity.setText(moMaterialRequest.getAuxProvEntName());
            jtfConsumeEntity.setText(moMaterialRequest.getConsumptionInfo());
            
            jtfProviderEntity.setToolTipText(jtfProviderEntity.getText());
            jtfConsumeEntity.setToolTipText(jtfConsumeEntity.getText());
            
            jtfProviderEntity.setCaretPosition(0);
            jtfConsumeEntity.setCaretPosition(0);

            jtfDate.setText(miClient.getSessionXXX().getFormatters().getDateFormat().format(moMaterialRequest.getDate()));
            jtfNumber.setText(String.format("%05d", moMaterialRequest.getNumber()));
            SDataUser oUserRequester = (SDataUser) SDataUtilities.readRegistry(miClient, SDataConstants.USRU_USR, new int[] { moMaterialRequest.getFkUserRequesterId() }, SLibConstants.EXEC_MODE_SILENT);
            jtfUser.setText(oUserRequester.getName());
            jtfCurrency.setText(SDataReadDescriptions.getCatalogueDescription(miClient, SDataConstants.CFGU_CUR, new int[] { 1 }, SLibConstants.DESCRIPTION_NAME));
            jtfExchangeRate.setText(miClient.getSessionXXX().getFormatters().getDecimalsExchangeRateFormat().format(1));

            jtfSubtotalCy_r.setText(miClient.getSessionXXX().getFormatters().getDecimalsValueFormat().format(moMaterialRequest.getTotal_r()));
            jtfTotalCy_r.setText(miClient.getSessionXXX().getFormatters().getDecimalsValueFormat().format(moMaterialRequest.getTotal_r()));

            jtfSubtotalCy_rCurKey.setText(SDataReadDescriptions.getCatalogueDescription(miClient, SDataConstants.CFGU_CUR, new int[] { 1 }, SLibConstants.DESCRIPTION_CODE));
            jtfTotalCy_rCurKey.setText(jtfSubtotalCy_rCurKey.getText());

            jckIsAuthorized.setSelected(SAuthorizationUtils.isAuthorized(miClient.getSession(), SAuthorizationUtils.AUTH_TYPE_MAT_REQUEST, moMaterialRequest.getPrimaryKey()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JCheckBox jckIsAuthorized;
    private javax.swing.JLabel jlConsumeEntity;
    private javax.swing.JLabel jlCurrency;
    private javax.swing.JLabel jlDate;
    private javax.swing.JLabel jlDpsType;
    private javax.swing.JLabel jlNumber;
    private javax.swing.JLabel jlProviderEntity;
    private javax.swing.JLabel jlSubtotalCy_r;
    private javax.swing.JLabel jlTaxRetainedCy_r;
    private javax.swing.JLabel jlTotalCy_r;
    private javax.swing.JLabel jlUserCreator;
    private javax.swing.JPanel jpDps;
    private javax.swing.JPanel jpDpsValue;
    private javax.swing.JTextField jtfConsumeEntity;
    private javax.swing.JTextField jtfCurrency;
    private javax.swing.JTextField jtfDate;
    private javax.swing.JTextField jtfDocumentType;
    private javax.swing.JTextField jtfExchangeRate;
    private javax.swing.JTextField jtfNumber;
    private javax.swing.JTextField jtfProviderEntity;
    private javax.swing.JTextField jtfSubtotalCy_r;
    private javax.swing.JTextField jtfSubtotalCy_rCurKey;
    private javax.swing.JTextField jtfTotalCy_r;
    private javax.swing.JTextField jtfTotalCy_rCurKey;
    private javax.swing.JTextField jtfUser;
    // End of variables declaration//GEN-END:variables

    public void setMaterialRequest(SDbMaterialRequest matRequest) {
        moMaterialRequest = matRequest;
        renderMaterialRequest();
    }
    
    public String getAuxUserRequesterName() {
        return jtfUser.getText();
    }
}
