/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SDialogItemPicker.java
 *
 * Created on 18/08/2023, 09:00:00 AM
 */

package erp.mod.trn.form;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import sa.lib.SLibConsts;
import sa.lib.SLibUtils;
import sa.lib.db.SDbConsts;
import sa.lib.grid.SGridColumnForm;
import sa.lib.grid.SGridConsts;
import sa.lib.grid.SGridPaneForm;
import sa.lib.grid.SGridRow;
import sa.lib.grid.SGridRowOptionPicker;
import sa.lib.grid.SGridUtils;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiOptionPicker;
import sa.lib.gui.SGuiOptionPickerSettings;
import sa.lib.gui.SGuiParams;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;

/**
 *
 * @author Sergio Flores, Isabel Servín
 */
public class SDialogItemPicker extends JDialog implements SGuiOptionPicker, KeyListener {

    public static JFrame OwnerFrame;

    protected SGuiClient miClient;
    protected int mnPickerType;
    protected int mnPickerSubtype;
    protected int mnPickerResult;
    protected boolean mbFirstActivation;
    protected SGuiOptionPickerSettings moSettings;
    protected SGridPaneForm moGridPicker;
    protected Vector<SGridRow> allRows;
    
    /** Creates new form SBeanOptionPicker */
    public SDialogItemPicker() {
        super(OwnerFrame, true);
        initComponents();
        initComponentsBean();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFilter = new javax.swing.JPanel();
        moTextItem = new sa.lib.gui.bean.SBeanFieldText();
        jpGrid = new javax.swing.JPanel();
        jpCommand = new javax.swing.JPanel();
        jbOk = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DBeanOptionPicker");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jpFilter.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar ítem:"));
        jpFilter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        moTextItem.setPreferredSize(new java.awt.Dimension(600, 23));
        jpFilter.add(moTextItem);

        getContentPane().add(jpFilter, java.awt.BorderLayout.PAGE_START);

        jpGrid.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar una opción:"));
        jpGrid.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jpGrid, java.awt.BorderLayout.CENTER);

        jpCommand.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jbOk.setText("Aceptar");
        jbOk.setMaximumSize(new java.awt.Dimension(75, 23));
        jbOk.setMinimumSize(new java.awt.Dimension(75, 23));
        jbOk.setPreferredSize(new java.awt.Dimension(75, 23));
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });
        jpCommand.add(jbOk);

        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jpCommand.add(jbCancel);

        getContentPane().add(jpCommand, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(656, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        actionOk();
    }//GEN-LAST:event_jbOkActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        actionCancel();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        windowActivated();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        windowClosed();
    }//GEN-LAST:event_formWindowClosed

    private void initComponentsBean() {
        SGuiUtils.setWindowBounds(this, 640, 400);

        moTextItem.addKeyListener(this);
        
        moGridPicker = null;
        SGuiUtils.createActionMap(rootPane, this, "actionCancel", "cancel", KeyEvent.VK_ESCAPE);
    }

    private void windowActivated() {
        if (mbFirstActivation) {
            mbFirstActivation = false;
            if (moGridPicker.getTable().getRowCount() > 0) {
                moGridPicker.getTable().requestFocus();
            }
            else {
                jbCancel.requestFocus();
            }
        }
    }

    private void windowClosed() {
        moGridPicker.paneViewClosed();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jbCancel;
    protected javax.swing.JButton jbOk;
    private javax.swing.JPanel jpCommand;
    private javax.swing.JPanel jpFilter;
    private javax.swing.JPanel jpGrid;
    private sa.lib.gui.bean.SBeanFieldText moTextItem;
    // End of variables declaration//GEN-END:variables

    /*
     * Protected methods
     */

    protected void resetBaseForm() {
        mnPickerResult = SLibConsts.UNDEFINED;
        mbFirstActivation = true;
    }

    protected void createGridPicker() {
        moGridPicker = new SGridPaneForm(miClient, mnPickerType, mnPickerSubtype, true, getTitle()) {

            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }

            @Override
            public ArrayList<SGridColumnForm> createGridColumns() {
                return moSettings.getGridColumns();
            }
        };

        moGridPicker.setForm(null);
        //moGridPicker.setOptionPickerOwner(this);
        jpGrid.removeAll();
        jpGrid.add(moGridPicker, BorderLayout.CENTER);
    }

    protected void populateGridPicker() {
        int col = 0;
        int cols = moSettings.getGridColumns().size();
        int[] key = null;
        Class colClass = null;
        ResultSet resultSet = null;
        SGridRowOptionPicker row = null;
        Vector<SGridRow> rows = new Vector<SGridRow>();

        try {
            resultSet = miClient.getSession().getStatement().executeQuery(moSettings.getSql());
            while (resultSet.next()) {
                if (moSettings.getPrimaryKeyLength() > 0) {
                    key = new int[moSettings.getPrimaryKeyLength()];
                    for (col = 0; col < moSettings.getPrimaryKeyLength(); col++) {
                        key[col] = resultSet.getInt(SDbConsts.FIELD_ID + (col + 1));
                    }
                }

                row = new SGridRowOptionPicker(key);
                for (col = 0; col < cols; col++) {
                    colClass = SGridUtils.getDataTypeClass(moSettings.getGridColumns().get(col).getColumnType());

                    if (colClass == Long.class) {
                        row.getValues().add(resultSet.getLong(SDbConsts.FIELD_PICK + (col + 1)));
                    }
                    else if (colClass == Integer.class) {
                        row.getValues().add(resultSet.getInt(SDbConsts.FIELD_PICK + (col + 1)));
                    }
                    else if (colClass == Double.class) {
                        row.getValues().add(resultSet.getDouble(SDbConsts.FIELD_PICK + (col + 1)));
                    }
                    else if (colClass == Float.class) {
                        row.getValues().add(resultSet.getFloat(SDbConsts.FIELD_PICK + (col + 1)));
                    }
                    else if (colClass == Boolean.class) {
                        row.getValues().add(resultSet.getBoolean(SDbConsts.FIELD_PICK + (col + 1)));
                    }
                    else if (colClass == String.class) {
                        row.getValues().add(resultSet.getString(SDbConsts.FIELD_PICK + (col + 1)));
                    }
                    else if (colClass == Date.class) {
                        switch (moSettings.getGridColumns().get(col).getColumnType()) {
                            case SGridConsts.COL_TYPE_DATE:
                                row.getValues().add(resultSet.getDate(SDbConsts.FIELD_PICK + (col + 1)));
                                break;
                            case SGridConsts.COL_TYPE_DATE_DATETIME:
                                row.getValues().add(resultSet.getTimestamp(SDbConsts.FIELD_PICK + (col + 1)));
                                break;
                            case SGridConsts.COL_TYPE_DATE_TIME:
                                row.getValues().add(resultSet.getTime(SDbConsts.FIELD_PICK + (col + 1)));
                                break;
                            default:
                                throw new Exception(SLibConsts.ERR_MSG_OPTION_UNKNOWN);
                        }
                    }
                    else {
                        throw new Exception(SLibConsts.ERR_MSG_OPTION_UNKNOWN);
                    }
                }

                if (moSettings.isMainOptionApplying()) {
                    switch (moSettings.getMainOptionDataType()) {
                        case SLibConsts.DATA_TYPE_INT:
                            row.setMainOption(resultSet.getLong(SDbConsts.FIELD_VALUE));
                            break;
                        case SLibConsts.DATA_TYPE_DEC:
                            row.setMainOption(resultSet.getDouble(SDbConsts.FIELD_VALUE));
                            break;
                        case SLibConsts.DATA_TYPE_BOOL:
                            row.setMainOption(resultSet.getBoolean(SDbConsts.FIELD_VALUE));
                            break;
                        case SLibConsts.DATA_TYPE_TEXT:
                            row.setMainOption(resultSet.getString(SDbConsts.FIELD_VALUE));
                            break;
                        case SLibConsts.DATA_TYPE_DATE:
                            row.setMainOption(resultSet.getDate(SDbConsts.FIELD_VALUE));
                            break;
                        default:
                            throw new Exception(SLibConsts.ERR_MSG_OPTION_UNKNOWN);
                    }
                }

                rows.add(row);
            }

            moGridPicker.populateGrid(rows);
            allRows = new Vector<>();
            allRows.addAll(rows);
        }
        catch (SQLException e) {
            SLibUtils.showException(this, e);
        }
        catch (Exception e) {
            SLibUtils.showException(this, e);
        }
    }

    /*
     * Public methods
     */

    public JPanel getBeanPanel() {
        return jpGrid;
    }
    
    public void setParams(SGuiParams params) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /*
     * Overriden methods
     */

    @Override
    public void setPickerSettings(final SGuiClient client, final int pickerType, final int pickerSubtype, final SGuiOptionPickerSettings settings) {
        miClient = client;
        mnPickerType = pickerType;
        mnPickerSubtype = pickerSubtype;
        moSettings = settings;
        createGridPicker();
        setTitle(moSettings.getTitle());
    }

     @Override
    public void resetPicker() {
        resetBaseForm();
        populateGridPicker();
    }

    @Override
    public void setPickerVisible(boolean visible) {
        setVisible(visible);
    }

    @Override
    public void setOption(Object option) {
        int row = -1;

        if (option != null) {
            if (moSettings.isMainOptionApplying()) {
                for (row = 0; row < moGridPicker.getModel().getRowCount(); row++) {
                    if (option == ((SGridRowOptionPicker) moGridPicker.getGridRow(row)).getMainOption()) {
                        break;
                    }
                }
            }
            else {
                for (row = 0; row < moGridPicker.getModel().getRowCount(); row++) {
                    if (SLibUtils.compareKeys(option, moGridPicker.getGridRow(row).getRowPrimaryKey())) {
                        break;
                    }
                }
            }

            if (row != -1) {
                moGridPicker.setSelectedGridRow(row);
            }
        }
    }

    @Override
    public Object getOption() {
        Object option = null;
        SGridRowOptionPicker row = (SGridRowOptionPicker) moGridPicker.getSelectedGridRow();

        if (row != null) {
            option = moSettings.isMainOptionApplying() ? row.getMainOption() : row.getRowPrimaryKey();
        }

        return option;
    }

    @Override
    public SGuiValidation validatePicker() {
        SGuiValidation validation = new SGuiValidation();

        if (moGridPicker.getSelectedGridRow() == null) {
            validation.setMessage(SGridConsts.MSG_SELECT_ROW);
            validation.setComponent(moGridPicker.getTable());
        }

        return validation;
    }

    @Override
    public int getPickerType() {
        return mnPickerType;
    }

    @Override
    public int getPickerSubtype() {
        return mnPickerSubtype;
    }

    @Override
    public int getPickerResult() {
        return mnPickerResult;
    }

    @Override
    public void actionOk() {
        if (jbOk.isEnabled()) {
            if (SGuiUtils.computeValidation(miClient, validatePicker())) {
                mnPickerResult = SGuiConsts.FORM_RESULT_OK;
                dispose();
            }
        }
    }

    @Override
    public void actionCancel() {
        if (jbCancel.isEnabled()) {
            mnPickerResult = SGuiConsts.FORM_RESULT_CANCEL;
            dispose();
        }
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        Vector items = new Vector();
        String name = moTextItem.getValue();
        if (name.isEmpty()) {
            items.addAll(allRows);
        }
        else {
            for (SGridRow item : allRows) {
                if (SLibUtils.textToAscii(((SGridRowOptionPicker) item).getValues().get(0).toString()).contains(SLibUtils.textToAscii(name).toUpperCase())) {
                    items.add(item);
                }
                else if (SLibUtils.textToAscii(((SGridRowOptionPicker) item).getValues().get(1).toString()).contains(SLibUtils.textToAscii(name).toUpperCase())) {
                    items.add(item);
                }
            }
        }
        moGridPicker.populateGrid(items);
    }
}
